!**********************************************************************************************************************************
! NOTE: The following lines of code were generated by a Matlab script called "Write_ChckOutLst.m"
!      using the parameters listed in the "OutListParameters.xlsx" Excel file. Any changes to these 
!      lines should be modified in the Matlab script and/or Excel worksheet as necessary. 
!----------------------------------------------------------------------------------------------------------------------------------
!> This routine checks to see if any requested output channel names (stored in the OutList(:)) are invalid. It returns a 
!! warning if any of the channels are not available outputs from the module.
!!  It assigns the settings for OutParam(:) (i.e, the index, name, and units of the output channels, WriteOutput(:)).
!!  the sign is set to 0 if the channel is invalid.
!! It sets assumes the value p%NumOuts has been set before this routine has been called, and it sets the values of p%OutParam here.
!! 
!! This routine was generated by Write_ChckOutLst.m using the parameters listed in OutListParameters.xlsx.
SUBROUTINE SetOutParam(OutList, p, ErrStat, ErrMsg )
!..................................................................................................................................
   
   IMPLICIT                        NONE
   
      ! Passed variables
   
   CHARACTER(ChanLen),        INTENT(IN)     :: OutList(:)                        !< The list of user-requested outputs
   TYPE(SrvD_ParameterType),    INTENT(INOUT)  :: p                                 !< The module parameters
   INTEGER(IntKi),            INTENT(OUT)    :: ErrStat                           !< The error status code
   CHARACTER(*),              INTENT(OUT)    :: ErrMsg                            !< The error message, if an error occurred
   
      ! Local variables
   
   INTEGER                      :: ErrStat2                                        ! temporary (local) error status
   INTEGER                      :: I                                               ! Generic loop-counting index
   INTEGER                      :: J                                               ! Generic loop-counting index
   INTEGER                      :: INDX                                            ! Index for valid arrays
   LOGICAL                      :: InvalidOutput(0:MaxOutPts)                      ! This array determines if the output channel is valid for this configuration
   CHARACTER(*), PARAMETER      :: RoutineName = "SetOutParam"
   
   CHARACTER(OutStrLenM1), PARAMETER  :: ValidParamAry(526) =  (/  &   ! This lists the names of the allowed parameters, which must be sorted alphabetically
                               "BLAIRFLC1   ","BLAIRFLC2   ","BLAIRFLC3   ","BLFLAP1     ","BLFLAP2     ","BLFLAP3     ", &
                               "BLPITCHC1   ","BLPITCHC2   ","BLPITCHC3   ","BSTC1_B1_FXI","BSTC1_B1_FXL","BSTC1_B1_FYI", &
                               "BSTC1_B1_FYL","BSTC1_B1_FZI","BSTC1_B1_FZL","BSTC1_B1_MXI","BSTC1_B1_MXL","BSTC1_B1_MYI", &
                               "BSTC1_B1_MYL","BSTC1_B1_MZI","BSTC1_B1_MZL","BSTC1_B1_XQ ","BSTC1_B1_XQD","BSTC1_B1_YQ ", &
                               "BSTC1_B1_YQD","BSTC1_B1_ZQ ","BSTC1_B1_ZQD","BSTC1_B2_FXI","BSTC1_B2_FXL","BSTC1_B2_FYI", &
                               "BSTC1_B2_FYL","BSTC1_B2_FZI","BSTC1_B2_FZL","BSTC1_B2_MXI","BSTC1_B2_MXL","BSTC1_B2_MYI", &
                               "BSTC1_B2_MYL","BSTC1_B2_MZI","BSTC1_B2_MZL","BSTC1_B2_XQ ","BSTC1_B2_XQD","BSTC1_B2_YQ ", &
                               "BSTC1_B2_YQD","BSTC1_B2_ZQ ","BSTC1_B2_ZQD","BSTC1_B3_FXI","BSTC1_B3_FXL","BSTC1_B3_FYI", &
                               "BSTC1_B3_FYL","BSTC1_B3_FZI","BSTC1_B3_FZL","BSTC1_B3_MXI","BSTC1_B3_MXL","BSTC1_B3_MYI", &
                               "BSTC1_B3_MYL","BSTC1_B3_MZI","BSTC1_B3_MZL","BSTC1_B3_XQ ","BSTC1_B3_XQD","BSTC1_B3_YQ ", &
                               "BSTC1_B3_YQD","BSTC1_B3_ZQ ","BSTC1_B3_ZQD","BSTC1_B4_FXI","BSTC1_B4_FXL","BSTC1_B4_FYI", &
                               "BSTC1_B4_FYL","BSTC1_B4_FZI","BSTC1_B4_FZL","BSTC1_B4_MXI","BSTC1_B4_MXL","BSTC1_B4_MYI", &
                               "BSTC1_B4_MYL","BSTC1_B4_MZI","BSTC1_B4_MZL","BSTC1_B4_XQ ","BSTC1_B4_XQD","BSTC1_B4_YQ ", &
                               "BSTC1_B4_YQD","BSTC1_B4_ZQ ","BSTC1_B4_ZQD","BSTC2_B1_FXI","BSTC2_B1_FXL","BSTC2_B1_FYI", &
                               "BSTC2_B1_FYL","BSTC2_B1_FZI","BSTC2_B1_FZL","BSTC2_B1_MXI","BSTC2_B1_MXL","BSTC2_B1_MYI", &
                               "BSTC2_B1_MYL","BSTC2_B1_MZI","BSTC2_B1_MZL","BSTC2_B1_XQ ","BSTC2_B1_XQD","BSTC2_B1_YQ ", &
                               "BSTC2_B1_YQD","BSTC2_B1_ZQ ","BSTC2_B1_ZQD","BSTC2_B2_FXI","BSTC2_B2_FXL","BSTC2_B2_FYI", &
                               "BSTC2_B2_FYL","BSTC2_B2_FZI","BSTC2_B2_FZL","BSTC2_B2_MXI","BSTC2_B2_MXL","BSTC2_B2_MYI", &
                               "BSTC2_B2_MYL","BSTC2_B2_MZI","BSTC2_B2_MZL","BSTC2_B2_XQ ","BSTC2_B2_XQD","BSTC2_B2_YQ ", &
                               "BSTC2_B2_YQD","BSTC2_B2_ZQ ","BSTC2_B2_ZQD","BSTC2_B3_FXI","BSTC2_B3_FXL","BSTC2_B3_FYI", &
                               "BSTC2_B3_FYL","BSTC2_B3_FZI","BSTC2_B3_FZL","BSTC2_B3_MXI","BSTC2_B3_MXL","BSTC2_B3_MYI", &
                               "BSTC2_B3_MYL","BSTC2_B3_MZI","BSTC2_B3_MZL","BSTC2_B3_XQ ","BSTC2_B3_XQD","BSTC2_B3_YQ ", &
                               "BSTC2_B3_YQD","BSTC2_B3_ZQ ","BSTC2_B3_ZQD","BSTC2_B4_FXI","BSTC2_B4_FXL","BSTC2_B4_FYI", &
                               "BSTC2_B4_FYL","BSTC2_B4_FZI","BSTC2_B4_FZL","BSTC2_B4_MXI","BSTC2_B4_MXL","BSTC2_B4_MYI", &
                               "BSTC2_B4_MYL","BSTC2_B4_MZI","BSTC2_B4_MZL","BSTC2_B4_XQ ","BSTC2_B4_XQD","BSTC2_B4_YQ ", &
                               "BSTC2_B4_YQD","BSTC2_B4_ZQ ","BSTC2_B4_ZQD","BSTC3_B1_FXI","BSTC3_B1_FXL","BSTC3_B1_FYI", &
                               "BSTC3_B1_FYL","BSTC3_B1_FZI","BSTC3_B1_FZL","BSTC3_B1_MXI","BSTC3_B1_MXL","BSTC3_B1_MYI", &
                               "BSTC3_B1_MYL","BSTC3_B1_MZI","BSTC3_B1_MZL","BSTC3_B1_XQ ","BSTC3_B1_XQD","BSTC3_B1_YQ ", &
                               "BSTC3_B1_YQD","BSTC3_B1_ZQ ","BSTC3_B1_ZQD","BSTC3_B2_FXI","BSTC3_B2_FXL","BSTC3_B2_FYI", &
                               "BSTC3_B2_FYL","BSTC3_B2_FZI","BSTC3_B2_FZL","BSTC3_B2_MXI","BSTC3_B2_MXL","BSTC3_B2_MYI", &
                               "BSTC3_B2_MYL","BSTC3_B2_MZI","BSTC3_B2_MZL","BSTC3_B2_XQ ","BSTC3_B2_XQD","BSTC3_B2_YQ ", &
                               "BSTC3_B2_YQD","BSTC3_B2_ZQ ","BSTC3_B2_ZQD","BSTC3_B3_FXI","BSTC3_B3_FXL","BSTC3_B3_FYI", &
                               "BSTC3_B3_FYL","BSTC3_B3_FZI","BSTC3_B3_FZL","BSTC3_B3_MXI","BSTC3_B3_MXL","BSTC3_B3_MYI", &
                               "BSTC3_B3_MYL","BSTC3_B3_MZI","BSTC3_B3_MZL","BSTC3_B3_XQ ","BSTC3_B3_XQD","BSTC3_B3_YQ ", &
                               "BSTC3_B3_YQD","BSTC3_B3_ZQ ","BSTC3_B3_ZQD","BSTC3_B4_FXI","BSTC3_B4_FXL","BSTC3_B4_FYI", &
                               "BSTC3_B4_FYL","BSTC3_B4_FZI","BSTC3_B4_FZL","BSTC3_B4_MXI","BSTC3_B4_MXL","BSTC3_B4_MYI", &
                               "BSTC3_B4_MYL","BSTC3_B4_MZI","BSTC3_B4_MZL","BSTC3_B4_XQ ","BSTC3_B4_XQD","BSTC3_B4_YQ ", &
                               "BSTC3_B4_YQD","BSTC3_B4_ZQ ","BSTC3_B4_ZQD","BSTC4_B1_FXI","BSTC4_B1_FXL","BSTC4_B1_FYI", &
                               "BSTC4_B1_FYL","BSTC4_B1_FZI","BSTC4_B1_FZL","BSTC4_B1_MXI","BSTC4_B1_MXL","BSTC4_B1_MYI", &
                               "BSTC4_B1_MYL","BSTC4_B1_MZI","BSTC4_B1_MZL","BSTC4_B1_XQ ","BSTC4_B1_XQD","BSTC4_B1_YQ ", &
                               "BSTC4_B1_YQD","BSTC4_B1_ZQ ","BSTC4_B1_ZQD","BSTC4_B2_FXI","BSTC4_B2_FXL","BSTC4_B2_FYI", &
                               "BSTC4_B2_FYL","BSTC4_B2_FZI","BSTC4_B2_FZL","BSTC4_B2_MXI","BSTC4_B2_MXL","BSTC4_B2_MYI", &
                               "BSTC4_B2_MYL","BSTC4_B2_MZI","BSTC4_B2_MZL","BSTC4_B2_XQ ","BSTC4_B2_XQD","BSTC4_B2_YQ ", &
                               "BSTC4_B2_YQD","BSTC4_B2_ZQ ","BSTC4_B2_ZQD","BSTC4_B3_FXI","BSTC4_B3_FXL","BSTC4_B3_FYI", &
                               "BSTC4_B3_FYL","BSTC4_B3_FZI","BSTC4_B3_FZL","BSTC4_B3_MXI","BSTC4_B3_MXL","BSTC4_B3_MYI", &
                               "BSTC4_B3_MYL","BSTC4_B3_MZI","BSTC4_B3_MZL","BSTC4_B3_XQ ","BSTC4_B3_XQD","BSTC4_B3_YQ ", &
                               "BSTC4_B3_YQD","BSTC4_B3_ZQ ","BSTC4_B3_ZQD","BSTC4_B4_FXI","BSTC4_B4_FXL","BSTC4_B4_FYI", &
                               "BSTC4_B4_FYL","BSTC4_B4_FZI","BSTC4_B4_FZL","BSTC4_B4_MXI","BSTC4_B4_MXL","BSTC4_B4_MYI", &
                               "BSTC4_B4_MYL","BSTC4_B4_MZI","BSTC4_B4_MZL","BSTC4_B4_XQ ","BSTC4_B4_XQD","BSTC4_B4_YQ ", &
                               "BSTC4_B4_YQD","BSTC4_B4_ZQ ","BSTC4_B4_ZQD","GENPWR      ","GENTQ       ","HSSBRTQC    ", &
                               "NSTC1_FXI   ","NSTC1_FXL   ","NSTC1_FYI   ","NSTC1_FYL   ","NSTC1_FZI   ","NSTC1_FZL   ", &
                               "NSTC1_MXI   ","NSTC1_MXL   ","NSTC1_MYI   ","NSTC1_MYL   ","NSTC1_MZI   ","NSTC1_MZL   ", &
                               "NSTC1_XQ    ","NSTC1_XQD   ","NSTC1_YQ    ","NSTC1_YQD   ","NSTC1_ZQ    ","NSTC1_ZQD   ", &
                               "NSTC2_FXI   ","NSTC2_FXL   ","NSTC2_FYI   ","NSTC2_FYL   ","NSTC2_FZI   ","NSTC2_FZL   ", &
                               "NSTC2_MXI   ","NSTC2_MXL   ","NSTC2_MYI   ","NSTC2_MYL   ","NSTC2_MZI   ","NSTC2_MZL   ", &
                               "NSTC2_XQ    ","NSTC2_XQD   ","NSTC2_YQ    ","NSTC2_YQD   ","NSTC2_ZQ    ","NSTC2_ZQD   ", &
                               "NSTC3_FXI   ","NSTC3_FXL   ","NSTC3_FYI   ","NSTC3_FYL   ","NSTC3_FZI   ","NSTC3_FZL   ", &
                               "NSTC3_MXI   ","NSTC3_MXL   ","NSTC3_MYI   ","NSTC3_MYL   ","NSTC3_MZI   ","NSTC3_MZL   ", &
                               "NSTC3_XQ    ","NSTC3_XQD   ","NSTC3_YQ    ","NSTC3_YQD   ","NSTC3_ZQ    ","NSTC3_ZQD   ", &
                               "NSTC4_FXI   ","NSTC4_FXL   ","NSTC4_FYI   ","NSTC4_FYL   ","NSTC4_FZI   ","NSTC4_FZL   ", &
                               "NSTC4_MXI   ","NSTC4_MXL   ","NSTC4_MYI   ","NSTC4_MYL   ","NSTC4_MZI   ","NSTC4_MZL   ", &
                               "NSTC4_XQ    ","NSTC4_XQD   ","NSTC4_YQ    ","NSTC4_YQD   ","NSTC4_ZQ    ","NSTC4_ZQD   ", &
                               "SSTC1_BQ    ","SSTC1_BQD   ","SSTC1_FXI   ","SSTC1_FXL   ","SSTC1_FYI   ","SSTC1_FYL   ", &
                               "SSTC1_FZI   ","SSTC1_FZL   ","SSTC1_MXI   ","SSTC1_MXL   ","SSTC1_MYI   ","SSTC1_MYL   ", &
                               "SSTC1_MZI   ","SSTC1_MZL   ","SSTC1_XQ    ","SSTC1_XQD   ","SSTC1_YQ    ","SSTC1_YQD   ", &
                               "SSTC1_ZQ    ","SSTC1_ZQD   ","SSTC2_BQ    ","SSTC2_BQD   ","SSTC2_FXI   ","SSTC2_FXL   ", &
                               "SSTC2_FYI   ","SSTC2_FYL   ","SSTC2_FZI   ","SSTC2_FZL   ","SSTC2_MXI   ","SSTC2_MXL   ", &
                               "SSTC2_MYI   ","SSTC2_MYL   ","SSTC2_MZI   ","SSTC2_MZL   ","SSTC2_XQ    ","SSTC2_XQD   ", &
                               "SSTC2_YQ    ","SSTC2_YQD   ","SSTC2_ZQ    ","SSTC2_ZQD   ","SSTC3_BQ    ","SSTC3_BQD   ", &
                               "SSTC3_FXI   ","SSTC3_FXL   ","SSTC3_FYI   ","SSTC3_FYL   ","SSTC3_FZI   ","SSTC3_FZL   ", &
                               "SSTC3_MXI   ","SSTC3_MXL   ","SSTC3_MYI   ","SSTC3_MYL   ","SSTC3_MZI   ","SSTC3_MZL   ", &
                               "SSTC3_XQ    ","SSTC3_XQD   ","SSTC3_YQ    ","SSTC3_YQD   ","SSTC3_ZQ    ","SSTC3_ZQD   ", &
                               "SSTC4_BQ    ","SSTC4_BQD   ","SSTC4_FXI   ","SSTC4_FXL   ","SSTC4_FYI   ","SSTC4_FYL   ", &
                               "SSTC4_FZI   ","SSTC4_FZL   ","SSTC4_MXI   ","SSTC4_MXL   ","SSTC4_MYI   ","SSTC4_MYL   ", &
                               "SSTC4_MZI   ","SSTC4_MZL   ","SSTC4_XQ    ","SSTC4_XQD   ","SSTC4_YQ    ","SSTC4_YQD   ", &
                               "SSTC4_ZQ    ","SSTC4_ZQD   ","TSTC1_FXI   ","TSTC1_FXL   ","TSTC1_FYI   ","TSTC1_FYL   ", &
                               "TSTC1_FZI   ","TSTC1_FZL   ","TSTC1_MXI   ","TSTC1_MXL   ","TSTC1_MYI   ","TSTC1_MYL   ", &
                               "TSTC1_MZI   ","TSTC1_MZL   ","TSTC1_XQ    ","TSTC1_XQD   ","TSTC1_YQ    ","TSTC1_YQD   ", &
                               "TSTC1_ZQ    ","TSTC1_ZQD   ","TSTC2_FXI   ","TSTC2_FXL   ","TSTC2_FYI   ","TSTC2_FYL   ", &
                               "TSTC2_FZI   ","TSTC2_FZL   ","TSTC2_MXI   ","TSTC2_MXL   ","TSTC2_MYI   ","TSTC2_MYL   ", &
                               "TSTC2_MZI   ","TSTC2_MZL   ","TSTC2_XQ    ","TSTC2_XQD   ","TSTC2_YQ    ","TSTC2_YQD   ", &
                               "TSTC2_ZQ    ","TSTC2_ZQD   ","TSTC3_FXI   ","TSTC3_FXL   ","TSTC3_FYI   ","TSTC3_FYL   ", &
                               "TSTC3_FZI   ","TSTC3_FZL   ","TSTC3_MXI   ","TSTC3_MXL   ","TSTC3_MYI   ","TSTC3_MYL   ", &
                               "TSTC3_MZI   ","TSTC3_MZL   ","TSTC3_XQ    ","TSTC3_XQD   ","TSTC3_YQ    ","TSTC3_YQD   ", &
                               "TSTC3_ZQ    ","TSTC3_ZQD   ","TSTC4_FXI   ","TSTC4_FXL   ","TSTC4_FYI   ","TSTC4_FYL   ", &
                               "TSTC4_FZI   ","TSTC4_FZL   ","TSTC4_MXI   ","TSTC4_MXL   ","TSTC4_MYI   ","TSTC4_MYL   ", &
                               "TSTC4_MZI   ","TSTC4_MZL   ","TSTC4_XQ    ","TSTC4_XQD   ","TSTC4_YQ    ","TSTC4_YQD   ", &
                               "TSTC4_ZQ    ","TSTC4_ZQD   ","YAWMOM      ","YAWMOMCOM   "/)
   INTEGER(IntKi), PARAMETER :: ParamIndxAry(526) =  (/ &                            ! This lists the index into AllOuts(:) of the allowed parameters ValidParamAry(:)
                                   BlAirFlC1 ,    BlAirFlC2 ,    BlAirFlC3 ,    BlAirFlC1 ,    BlAirFlC2 ,    BlAirFlC3 , &
                                   BlPitchC1 ,    BlPitchC2 ,    BlPitchC3 , BStC1_B1_Fxi , BStC1_B1_Fxl , BStC1_B1_Fyi , &
                                BStC1_B1_Fyl , BStC1_B1_Fzi , BStC1_B1_Fzl , BStC1_B1_Mxi , BStC1_B1_Mxl , BStC1_B1_Myi , &
                                BStC1_B1_Myl , BStC1_B1_Mzi , BStC1_B1_Mzl ,  BStC1_B1_XQ , BStC1_B1_XQD ,  BStC1_B1_YQ , &
                                BStC1_B1_YQD ,  BStC1_B1_ZQ , BStC1_B1_ZQD , BStC1_B2_Fxi , BStC1_B2_Fxl , BStC1_B2_Fyi , &
                                BStC1_B2_Fyl , BStC1_B2_Fzi , BStC1_B2_Fzl , BStC1_B2_Mxi , BStC1_B2_Mxl , BStC1_B2_Myi , &
                                BStC1_B2_Myl , BStC1_B2_Mzi , BStC1_B2_Mzl ,  BStC1_B2_XQ , BStC1_B2_XQD ,  BStC1_B2_YQ , &
                                BStC1_B2_YQD ,  BStC1_B2_ZQ , BStC1_B2_ZQD , BStC1_B3_Fxi , BStC1_B3_Fxl , BStC1_B3_Fyi , &
                                BStC1_B3_Fyl , BStC1_B3_Fzi , BStC1_B3_Fzl , BStC1_B3_Mxi , BStC1_B3_Mxl , BStC1_B3_Myi , &
                                BStC1_B3_Myl , BStC1_B3_Mzi , BStC1_B3_Mzl ,  BStC1_B3_XQ , BStC1_B3_XQD ,  BStC1_B3_YQ , &
                                BStC1_B3_YQD ,  BStC1_B3_ZQ , BStC1_B3_ZQD , BStC1_B4_Fxi , BStC1_B4_Fxl , BStC1_B4_Fyi , &
                                BStC1_B4_Fyl , BStC1_B4_Fzi , BStC1_B4_Fzl , BStC1_B4_Mxi , BStC1_B4_Mxl , BStC1_B4_Myi , &
                                BStC1_B4_Myl , BStC1_B4_Mzi , BStC1_B4_Mzl ,  BStC1_B4_XQ , BStC1_B4_XQD ,  BStC1_B4_YQ , &
                                BStC1_B4_YQD ,  BStC1_B4_ZQ , BStC1_B4_ZQD , BStC2_B1_Fxi , BStC2_B1_Fxl , BStC2_B1_Fyi , &
                                BStC2_B1_Fyl , BStC2_B1_Fzi , BStC2_B1_Fzl , BStC2_B1_Mxi , BStC2_B1_Mxl , BStC2_B1_Myi , &
                                BStC2_B1_Myl , BStC2_B1_Mzi , BStC2_B1_Mzl ,  BStC2_B1_XQ , BStC2_B1_XQD ,  BStC2_B1_YQ , &
                                BStC2_B1_YQD ,  BStC2_B1_ZQ , BStC2_B1_ZQD , BStC2_B2_Fxi , BStC2_B2_Fxl , BStC2_B2_Fyi , &
                                BStC2_B2_Fyl , BStC2_B2_Fzi , BStC2_B2_Fzl , BStC2_B2_Mxi , BStC2_B2_Mxl , BStC2_B2_Myi , &
                                BStC2_B2_Myl , BStC2_B2_Mzi , BStC2_B2_Mzl ,  BStC2_B2_XQ , BStC2_B2_XQD ,  BStC2_B2_YQ , &
                                BStC2_B2_YQD ,  BStC2_B2_ZQ , BStC2_B2_ZQD , BStC2_B3_Fxi , BStC2_B3_Fxl , BStC2_B3_Fyi , &
                                BStC2_B3_Fyl , BStC2_B3_Fzi , BStC2_B3_Fzl , BStC2_B3_Mxi , BStC2_B3_Mxl , BStC2_B3_Myi , &
                                BStC2_B3_Myl , BStC2_B3_Mzi , BStC2_B3_Mzl ,  BStC2_B3_XQ , BStC2_B3_XQD ,  BStC2_B3_YQ , &
                                BStC2_B3_YQD ,  BStC2_B3_ZQ , BStC2_B3_ZQD , BStC2_B4_Fxi , BStC2_B4_Fxl , BStC2_B4_Fyi , &
                                BStC2_B4_Fyl , BStC2_B4_Fzi , BStC2_B4_Fzl , BStC2_B4_Mxi , BStC2_B4_Mxl , BStC2_B4_Myi , &
                                BStC2_B4_Myl , BStC2_B4_Mzi , BStC2_B4_Mzl ,  BStC2_B4_XQ , BStC2_B4_XQD ,  BStC2_B4_YQ , &
                                BStC2_B4_YQD ,  BStC2_B4_ZQ , BStC2_B4_ZQD , BStC3_B1_Fxi , BStC3_B1_Fxl , BStC3_B1_Fyi , &
                                BStC3_B1_Fyl , BStC3_B1_Fzi , BStC3_B1_Fzl , BStC3_B1_Mxi , BStC3_B1_Mxl , BStC3_B1_Myi , &
                                BStC3_B1_Myl , BStC3_B1_Mzi , BStC3_B1_Mzl ,  BStC3_B1_XQ , BStC3_B1_XQD ,  BStC3_B1_YQ , &
                                BStC3_B1_YQD ,  BStC3_B1_ZQ , BStC3_B1_ZQD , BStC3_B2_Fxi , BStC3_B2_Fxl , BStC3_B2_Fyi , &
                                BStC3_B2_Fyl , BStC3_B2_Fzi , BStC3_B2_Fzl , BStC3_B2_Mxi , BStC3_B2_Mxl , BStC3_B2_Myi , &
                                BStC3_B2_Myl , BStC3_B2_Mzi , BStC3_B2_Mzl ,  BStC3_B2_XQ , BStC3_B2_XQD ,  BStC3_B2_YQ , &
                                BStC3_B2_YQD ,  BStC3_B2_ZQ , BStC3_B2_ZQD , BStC3_B3_Fxi , BStC3_B3_Fxl , BStC3_B3_Fyi , &
                                BStC3_B3_Fyl , BStC3_B3_Fzi , BStC3_B3_Fzl , BStC3_B3_Mxi , BStC3_B3_Mxl , BStC3_B3_Myi , &
                                BStC3_B3_Myl , BStC3_B3_Mzi , BStC3_B3_Mzl ,  BStC3_B3_XQ , BStC3_B3_XQD ,  BStC3_B3_YQ , &
                                BStC3_B3_YQD ,  BStC3_B3_ZQ , BStC3_B3_ZQD , BStC3_B4_Fxi , BStC3_B4_Fxl , BStC3_B4_Fyi , &
                                BStC3_B4_Fyl , BStC3_B4_Fzi , BStC3_B4_Fzl , BStC3_B4_Mxi , BStC3_B4_Mxl , BStC3_B4_Myi , &
                                BStC3_B4_Myl , BStC3_B4_Mzi , BStC3_B4_Mzl ,  BStC3_B4_XQ , BStC3_B4_XQD ,  BStC3_B4_YQ , &
                                BStC3_B4_YQD ,  BStC3_B4_ZQ , BStC3_B4_ZQD , BStC4_B1_Fxi , BStC4_B1_Fxl , BStC4_B1_Fyi , &
                                BStC4_B1_Fyl , BStC4_B1_Fzi , BStC4_B1_Fzl , BStC4_B1_Mxi , BStC4_B1_Mxl , BStC4_B1_Myi , &
                                BStC4_B1_Myl , BStC4_B1_Mzi , BStC4_B1_Mzl ,  BStC4_B1_XQ , BStC4_B1_XQD ,  BStC4_B1_YQ , &
                                BStC4_B1_YQD ,  BStC4_B1_ZQ , BStC4_B1_ZQD , BStC4_B2_Fxi , BStC4_B2_Fxl , BStC4_B2_Fyi , &
                                BStC4_B2_Fyl , BStC4_B2_Fzi , BStC4_B2_Fzl , BStC4_B2_Mxi , BStC4_B2_Mxl , BStC4_B2_Myi , &
                                BStC4_B2_Myl , BStC4_B2_Mzi , BStC4_B2_Mzl ,  BStC4_B2_XQ , BStC4_B2_XQD ,  BStC4_B2_YQ , &
                                BStC4_B2_YQD ,  BStC4_B2_ZQ , BStC4_B2_ZQD , BStC4_B3_Fxi , BStC4_B3_Fxl , BStC4_B3_Fyi , &
                                BStC4_B3_Fyl , BStC4_B3_Fzi , BStC4_B3_Fzl , BStC4_B3_Mxi , BStC4_B3_Mxl , BStC4_B3_Myi , &
                                BStC4_B3_Myl , BStC4_B3_Mzi , BStC4_B3_Mzl ,  BStC4_B3_XQ , BStC4_B3_XQD ,  BStC4_B3_YQ , &
                                BStC4_B3_YQD ,  BStC4_B3_ZQ , BStC4_B3_ZQD , BStC4_B4_Fxi , BStC4_B4_Fxl , BStC4_B4_Fyi , &
                                BStC4_B4_Fyl , BStC4_B4_Fzi , BStC4_B4_Fzl , BStC4_B4_Mxi , BStC4_B4_Mxl , BStC4_B4_Myi , &
                                BStC4_B4_Myl , BStC4_B4_Mzi , BStC4_B4_Mzl ,  BStC4_B4_XQ , BStC4_B4_XQD ,  BStC4_B4_YQ , &
                                BStC4_B4_YQD ,  BStC4_B4_ZQ , BStC4_B4_ZQD ,       GenPwr ,        GenTq ,     HSSBrTqC , &
                                   NStC1_Fxi ,    NStC1_Fxl ,    NStC1_Fyi ,    NStC1_Fyl ,    NStC1_Fzi ,    NStC1_Fzl , &
                                   NStC1_Mxi ,    NStC1_Mxl ,    NStC1_Myi ,    NStC1_Myl ,    NStC1_Mzi ,    NStC1_Mzl , &
                                    NStC1_XQ ,    NStC1_XQD ,     NStC1_YQ ,    NStC1_YQD ,     NStC1_ZQ ,    NStC1_ZQD , &
                                   NStC2_Fxi ,    NStC2_Fxl ,    NStC2_Fyi ,    NStC2_Fyl ,    NStC2_Fzi ,    NStC2_Fzl , &
                                   NStC2_Mxi ,    NStC2_Mxl ,    NStC2_Myi ,    NStC2_Myl ,    NStC2_Mzi ,    NStC2_Mzl , &
                                    NStC2_XQ ,    NStC2_XQD ,     NStC2_YQ ,    NStC2_YQD ,     NStC2_ZQ ,    NStC2_ZQD , &
                                   NStC3_Fxi ,    NStC3_Fxl ,    NStC3_Fyi ,    NStC3_Fyl ,    NStC3_Fzi ,    NStC3_Fzl , &
                                   NStC3_Mxi ,    NStC3_Mxl ,    NStC3_Myi ,    NStC3_Myl ,    NStC3_Mzi ,    NStC3_Mzl , &
                                    NStC3_XQ ,    NStC3_XQD ,     NStC3_YQ ,    NStC3_YQD ,     NStC3_ZQ ,    NStC3_ZQD , &
                                   NStC4_Fxi ,    NStC4_Fxl ,    NStC4_Fyi ,    NStC4_Fyl ,    NStC4_Fzi ,    NStC4_Fzl , &
                                   NStC4_Mxi ,    NStC4_Mxl ,    NStC4_Myi ,    NStC4_Myl ,    NStC4_Mzi ,    NStC4_Mzl , &
                                    NStC4_XQ ,    NStC4_XQD ,     NStC4_YQ ,    NStC4_YQD ,     NStC4_ZQ ,    NStC4_ZQD , &
                                    SStC1_bQ ,    SStC1_bQD ,    SStC1_Fxi ,    SStC1_Fxl ,    SStC1_Fyi ,    SStC1_Fyl , &
                                   SStC1_Fzi ,    SStC1_Fzl ,    SStC1_Mxi ,    SStC1_Mxl ,    SStC1_Myi ,    SStC1_Myl , &
                                   SStC1_Mzi ,    SStC1_Mzl ,     SStC1_XQ ,    SStC1_XQD ,     SStC1_YQ ,    SStC1_YQD , &
                                    SStC1_ZQ ,    SStC1_ZQD ,     SStC2_bQ ,    SStC2_bQD ,    SStC2_Fxi ,    SStC2_Fxl , &
                                   SStC2_Fyi ,    SStC2_Fyl ,    SStC2_Fzi ,    SStC2_Fzl ,    SStC2_Mxi ,    SStC2_Mxl , &
                                   SStC2_Myi ,    SStC2_Myl ,    SStC2_Mzi ,    SStC2_Mzl ,     SStC2_XQ ,    SStC2_XQD , &
                                    SStC2_YQ ,    SStC2_YQD ,     SStC2_ZQ ,    SStC2_ZQD ,     SStC3_bQ ,    SStC3_bQD , &
                                   SStC3_Fxi ,    SStC3_Fxl ,    SStC3_Fyi ,    SStC3_Fyl ,    SStC3_Fzi ,    SStC3_Fzl , &
                                   SStC3_Mxi ,    SStC3_Mxl ,    SStC3_Myi ,    SStC3_Myl ,    SStC3_Mzi ,    SStC3_Mzl , &
                                    SStC3_XQ ,    SStC3_XQD ,     SStC3_YQ ,    SStC3_YQD ,     SStC3_ZQ ,    SStC3_ZQD , &
                                    SStC4_bQ ,    SStC4_bQD ,    SStC4_Fxi ,    SStC4_Fxl ,    SStC4_Fyi ,    SStC4_Fyl , &
                                   SStC4_Fzi ,    SStC4_Fzl ,    SStC4_Mxi ,    SStC4_Mxl ,    SStC4_Myi ,    SStC4_Myl , &
                                   SStC4_Mzi ,    SStC4_Mzl ,     SStC4_XQ ,    SStC4_XQD ,     SStC4_YQ ,    SStC4_YQD , &
                                    SStC4_ZQ ,    SStC4_ZQD ,    TStC1_Fxi ,    TStC1_Fxl ,    TStC1_Fyi ,    TStC1_Fyl , &
                                   TStC1_Fzi ,    TStC1_Fzl ,    TStC1_Mxi ,    TStC1_Mxl ,    TStC1_Myi ,    TStC1_Myl , &
                                   TStC1_Mzi ,    TStC1_Mzl ,     TStC1_XQ ,    TStC1_XQD ,     TStC1_YQ ,    TStC1_YQD , &
                                    TStC1_ZQ ,    TStC1_ZQD ,    TStC2_Fxi ,    TStC2_Fxl ,    TStC2_Fyi ,    TStC2_Fyl , &
                                   TStC2_Fzi ,    TStC2_Fzl ,    TStC2_Mxi ,    TStC2_Mxl ,    TStC2_Myi ,    TStC2_Myl , &
                                   TStC2_Mzi ,    TStC2_Mzl ,     TStC2_XQ ,    TStC2_XQD ,     TStC2_YQ ,    TStC2_YQD , &
                                    TStC2_ZQ ,    TStC2_ZQD ,    TStC3_Fxi ,    TStC3_Fxl ,    TStC3_Fyi ,    TStC3_Fyl , &
                                   TStC3_Fzi ,    TStC3_Fzl ,    TStC3_Mxi ,    TStC3_Mxl ,    TStC3_Myi ,    TStC3_Myl , &
                                   TStC3_Mzi ,    TStC3_Mzl ,     TStC3_XQ ,    TStC3_XQD ,     TStC3_YQ ,    TStC3_YQD , &
                                    TStC3_ZQ ,    TStC3_ZQD ,    TStC4_Fxi ,    TStC4_Fxl ,    TStC4_Fyi ,    TStC4_Fyl , &
                                   TStC4_Fzi ,    TStC4_Fzl ,    TStC4_Mxi ,    TStC4_Mxl ,    TStC4_Myi ,    TStC4_Myl , &
                                   TStC4_Mzi ,    TStC4_Mzl ,     TStC4_XQ ,    TStC4_XQD ,     TStC4_YQ ,    TStC4_YQD , &
                                    TStC4_ZQ ,    TStC4_ZQD ,    YawMomCom ,    YawMomCom /)
   CHARACTER(ChanLen), PARAMETER :: ParamUnitsAry(526) =  (/ character(ChanLen) :: &  ! This lists the units corresponding to the allowed parameters
                               "(-)   ","(-)   ","(-)   ","(-)   ","(-)   ","(-)   ", &
                               "(deg) ","(deg) ","(deg) ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN)  ","(kN)  ","(kN)  ","(kN-m)","(kN-m)","(kN-m)", &
                               "(kN-m)","(kN-m)","(kN-m)","(m)   ","(m/s) ","(m)   ", &
                               "(m/s) ","(m)   ","(m/s) ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN)  ","(kN)  ","(kN)  ","(kN-m)","(kN-m)","(kN-m)", &
                               "(kN-m)","(kN-m)","(kN-m)","(m)   ","(m/s) ","(m)   ", &
                               "(m/s) ","(m)   ","(m/s) ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN)  ","(kN)  ","(kN)  ","(kN-m)","(kN-m)","(kN-m)", &
                               "(kN-m)","(kN-m)","(kN-m)","(m)   ","(m/s) ","(m)   ", &
                               "(m/s) ","(m)   ","(m/s) ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN)  ","(kN)  ","(kN)  ","(kN-m)","(kN-m)","(kN-m)", &
                               "(kN-m)","(kN-m)","(kN-m)","(m)   ","(m/s) ","(m)   ", &
                               "(m/s) ","(m)   ","(m/s) ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN)  ","(kN)  ","(kN)  ","(kN-m)","(kN-m)","(kN-m)", &
                               "(kN-m)","(kN-m)","(kN-m)","(m)   ","(m/s) ","(m)   ", &
                               "(m/s) ","(m)   ","(m/s) ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN)  ","(kN)  ","(kN)  ","(kN-m)","(kN-m)","(kN-m)", &
                               "(kN-m)","(kN-m)","(kN-m)","(m)   ","(m/s) ","(m)   ", &
                               "(m/s) ","(m)   ","(m/s) ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN)  ","(kN)  ","(kN)  ","(kN-m)","(kN-m)","(kN-m)", &
                               "(kN-m)","(kN-m)","(kN-m)","(m)   ","(m/s) ","(m)   ", &
                               "(m/s) ","(m)   ","(m/s) ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN)  ","(kN)  ","(kN)  ","(kN-m)","(kN-m)","(kN-m)", &
                               "(kN-m)","(kN-m)","(kN-m)","(m)   ","(m/s) ","(m)   ", &
                               "(m/s) ","(m)   ","(m/s) ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN)  ","(kN)  ","(kN)  ","(kN-m)","(kN-m)","(kN-m)", &
                               "(kN-m)","(kN-m)","(kN-m)","(m)   ","(m/s) ","(m)   ", &
                               "(m/s) ","(m)   ","(m/s) ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN)  ","(kN)  ","(kN)  ","(kN-m)","(kN-m)","(kN-m)", &
                               "(kN-m)","(kN-m)","(kN-m)","(m)   ","(m/s) ","(m)   ", &
                               "(m/s) ","(m)   ","(m/s) ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN)  ","(kN)  ","(kN)  ","(kN-m)","(kN-m)","(kN-m)", &
                               "(kN-m)","(kN-m)","(kN-m)","(m)   ","(m/s) ","(m)   ", &
                               "(m/s) ","(m)   ","(m/s) ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN)  ","(kN)  ","(kN)  ","(kN-m)","(kN-m)","(kN-m)", &
                               "(kN-m)","(kN-m)","(kN-m)","(m)   ","(m/s) ","(m)   ", &
                               "(m/s) ","(m)   ","(m/s) ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN)  ","(kN)  ","(kN)  ","(kN-m)","(kN-m)","(kN-m)", &
                               "(kN-m)","(kN-m)","(kN-m)","(m)   ","(m/s) ","(m)   ", &
                               "(m/s) ","(m)   ","(m/s) ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN)  ","(kN)  ","(kN)  ","(kN-m)","(kN-m)","(kN-m)", &
                               "(kN-m)","(kN-m)","(kN-m)","(m)   ","(m/s) ","(m)   ", &
                               "(m/s) ","(m)   ","(m/s) ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN)  ","(kN)  ","(kN)  ","(kN-m)","(kN-m)","(kN-m)", &
                               "(kN-m)","(kN-m)","(kN-m)","(m)   ","(m/s) ","(m)   ", &
                               "(m/s) ","(m)   ","(m/s) ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN)  ","(kN)  ","(kN)  ","(kN-m)","(kN-m)","(kN-m)", &
                               "(kN-m)","(kN-m)","(kN-m)","(m)   ","(m/s) ","(m)   ", &
                               "(m/s) ","(m)   ","(m/s) ","(kW)  ","(kN-m)","(kN-m)", &
                               "(kN)  ","(kN)  ","(kN)  ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN-m)","(kN-m)","(kN-m)","(kN-m)","(kN-m)","(kN-m)", &
                               "(m)   ","(m/s) ","(m)   ","(m/s) ","(m)   ","(m/s) ", &
                               "(kN)  ","(kN)  ","(kN)  ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN-m)","(kN-m)","(kN-m)","(kN-m)","(kN-m)","(kN-m)", &
                               "(m)   ","(m/s) ","(m)   ","(m/s) ","(m)   ","(m/s) ", &
                               "(kN)  ","(kN)  ","(kN)  ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN-m)","(kN-m)","(kN-m)","(kN-m)","(kN-m)","(kN-m)", &
                               "(m)   ","(m/s) ","(m)   ","(m/s) ","(m)   ","(m/s) ", &
                               "(kN)  ","(kN)  ","(kN)  ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN-m)","(kN-m)","(kN-m)","(kN-m)","(kN-m)","(kN-m)", &
                               "(m)   ","(m/s) ","(m)   ","(m/s) ","(m)   ","(m/s) ", &
                               "(m)   ","(m/s) ","(kN)  ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN)  ","(kN)  ","(kN-m)","(kN-m)","(kN-m)","(kN-m)", &
                               "(kN-m)","(kN-m)","(m)   ","(m/s) ","(m)   ","(m/s) ", &
                               "(m)   ","(m/s) ","(m)   ","(m/s) ","(kN)  ","(kN)  ", &
                               "(kN)  ","(kN)  ","(kN)  ","(kN)  ","(kN-m)","(kN-m)", &
                               "(kN-m)","(kN-m)","(kN-m)","(kN-m)","(m)   ","(m/s) ", &
                               "(m)   ","(m/s) ","(m)   ","(m/s) ","(m)   ","(m/s) ", &
                               "(kN)  ","(kN)  ","(kN)  ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN-m)","(kN-m)","(kN-m)","(kN-m)","(kN-m)","(kN-m)", &
                               "(m)   ","(m/s) ","(m)   ","(m/s) ","(m)   ","(m/s) ", &
                               "(m)   ","(m/s) ","(kN)  ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN)  ","(kN)  ","(kN-m)","(kN-m)","(kN-m)","(kN-m)", &
                               "(kN-m)","(kN-m)","(m)   ","(m/s) ","(m)   ","(m/s) ", &
                               "(m)   ","(m/s) ","(kN)  ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN)  ","(kN)  ","(kN-m)","(kN-m)","(kN-m)","(kN-m)", &
                               "(kN-m)","(kN-m)","(m)   ","(m/s) ","(m)   ","(m/s) ", &
                               "(m)   ","(m/s) ","(kN)  ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN)  ","(kN)  ","(kN-m)","(kN-m)","(kN-m)","(kN-m)", &
                               "(kN-m)","(kN-m)","(m)   ","(m/s) ","(m)   ","(m/s) ", &
                               "(m)   ","(m/s) ","(kN)  ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN)  ","(kN)  ","(kN-m)","(kN-m)","(kN-m)","(kN-m)", &
                               "(kN-m)","(kN-m)","(m)   ","(m/s) ","(m)   ","(m/s) ", &
                               "(m)   ","(m/s) ","(kN)  ","(kN)  ","(kN)  ","(kN)  ", &
                               "(kN)  ","(kN)  ","(kN-m)","(kN-m)","(kN-m)","(kN-m)", &
                               "(kN-m)","(kN-m)","(m)   ","(m/s) ","(m)   ","(m/s) ", &
                               "(m)   ","(m/s) ","(kN-m)","(kN-m)"/)


      ! Initialize values
   ErrStat = ErrID_None
   ErrMsg = ""
   InvalidOutput = .FALSE.


      ! Determine which inputs are not valid

   InvalidOutput(   BlAirFlC3) = ( p%NumBl < 3 )
   InvalidOutput(   BlPitchC3) = ( p%NumBl < 3 )
   InvalidOutput(    NStC1_XQ) = ( p%NumNStC<1 )
   InvalidOutput(   NStC1_XQD) = ( p%NumNStC<1 )
   InvalidOutput(    NStC1_YQ) = ( p%NumNStC<1 )
   InvalidOutput(   NStC1_YQD) = ( p%NumNStC<1 )
   InvalidOutput(    NStC1_ZQ) = ( p%NumNStC<1 )
   InvalidOutput(   NStC1_ZQD) = ( p%NumNStC<1 )
   InvalidOutput(   NStC1_Fxi) = ( p%NumNStC<1 )
   InvalidOutput(   NStC1_Fyi) = ( p%NumNStC<1 )
   InvalidOutput(   NStC1_Fzi) = ( p%NumNStC<1 )
   InvalidOutput(   NStC1_Mxi) = ( p%NumNStC<1 )
   InvalidOutput(   NStC1_Myi) = ( p%NumNStC<1 )
   InvalidOutput(   NStC1_Mzi) = ( p%NumNStC<1 )
   InvalidOutput(   NStC1_Fxl) = ( p%NumNStC<1 )
   InvalidOutput(   NStC1_Fyl) = ( p%NumNStC<1 )
   InvalidOutput(   NStC1_Fzl) = ( p%NumNStC<1 )
   InvalidOutput(   NStC1_Mxl) = ( p%NumNStC<1 )
   InvalidOutput(   NStC1_Myl) = ( p%NumNStC<1 )
   InvalidOutput(   NStC1_Mzl) = ( p%NumNStC<1 )
   InvalidOutput(    NStC2_XQ) = ( p%NumNStC<2 )
   InvalidOutput(   NStC2_XQD) = ( p%NumNStC<2 )
   InvalidOutput(    NStC2_YQ) = ( p%NumNStC<2 )
   InvalidOutput(   NStC2_YQD) = ( p%NumNStC<2 )
   InvalidOutput(    NStC2_ZQ) = ( p%NumNStC<2 )
   InvalidOutput(   NStC2_ZQD) = ( p%NumNStC<2 )
   InvalidOutput(   NStC2_Fxi) = ( p%NumNStC<2 )
   InvalidOutput(   NStC2_Fyi) = ( p%NumNStC<2 )
   InvalidOutput(   NStC2_Fzi) = ( p%NumNStC<2 )
   InvalidOutput(   NStC2_Mxi) = ( p%NumNStC<2 )
   InvalidOutput(   NStC2_Myi) = ( p%NumNStC<2 )
   InvalidOutput(   NStC2_Mzi) = ( p%NumNStC<2 )
   InvalidOutput(   NStC2_Fxl) = ( p%NumNStC<2 )
   InvalidOutput(   NStC2_Fyl) = ( p%NumNStC<2 )
   InvalidOutput(   NStC2_Fzl) = ( p%NumNStC<2 )
   InvalidOutput(   NStC2_Mxl) = ( p%NumNStC<2 )
   InvalidOutput(   NStC2_Myl) = ( p%NumNStC<2 )
   InvalidOutput(   NStC2_Mzl) = ( p%NumNStC<2 )
   InvalidOutput(    NStC3_XQ) = ( p%NumNStC<3 )
   InvalidOutput(   NStC3_XQD) = ( p%NumNStC<3 )
   InvalidOutput(    NStC3_YQ) = ( p%NumNStC<3 )
   InvalidOutput(   NStC3_YQD) = ( p%NumNStC<3 )
   InvalidOutput(    NStC3_ZQ) = ( p%NumNStC<3 )
   InvalidOutput(   NStC3_ZQD) = ( p%NumNStC<3 )
   InvalidOutput(   NStC3_Fxi) = ( p%NumNStC<3 )
   InvalidOutput(   NStC3_Fyi) = ( p%NumNStC<3 )
   InvalidOutput(   NStC3_Fzi) = ( p%NumNStC<3 )
   InvalidOutput(   NStC3_Mxi) = ( p%NumNStC<3 )
   InvalidOutput(   NStC3_Myi) = ( p%NumNStC<3 )
   InvalidOutput(   NStC3_Mzi) = ( p%NumNStC<3 )
   InvalidOutput(   NStC3_Fxl) = ( p%NumNStC<3 )
   InvalidOutput(   NStC3_Fyl) = ( p%NumNStC<3 )
   InvalidOutput(   NStC3_Fzl) = ( p%NumNStC<3 )
   InvalidOutput(   NStC3_Mxl) = ( p%NumNStC<3 )
   InvalidOutput(   NStC3_Myl) = ( p%NumNStC<3 )
   InvalidOutput(   NStC3_Mzl) = ( p%NumNStC<3 )
   InvalidOutput(    NStC4_XQ) = ( p%NumNStC<4 )
   InvalidOutput(   NStC4_XQD) = ( p%NumNStC<4 )
   InvalidOutput(    NStC4_YQ) = ( p%NumNStC<4 )
   InvalidOutput(   NStC4_YQD) = ( p%NumNStC<4 )
   InvalidOutput(    NStC4_ZQ) = ( p%NumNStC<4 )
   InvalidOutput(   NStC4_ZQD) = ( p%NumNStC<4 )
   InvalidOutput(   NStC4_Fxi) = ( p%NumNStC<4 )
   InvalidOutput(   NStC4_Fyi) = ( p%NumNStC<4 )
   InvalidOutput(   NStC4_Fzi) = ( p%NumNStC<4 )
   InvalidOutput(   NStC4_Mxi) = ( p%NumNStC<4 )
   InvalidOutput(   NStC4_Myi) = ( p%NumNStC<4 )
   InvalidOutput(   NStC4_Mzi) = ( p%NumNStC<4 )
   InvalidOutput(   NStC4_Fxl) = ( p%NumNStC<4 )
   InvalidOutput(   NStC4_Fyl) = ( p%NumNStC<4 )
   InvalidOutput(   NStC4_Fzl) = ( p%NumNStC<4 )
   InvalidOutput(   NStC4_Mxl) = ( p%NumNStC<4 )
   InvalidOutput(   NStC4_Myl) = ( p%NumNStC<4 )
   InvalidOutput(   NStC4_Mzl) = ( p%NumNStC<4 )
   InvalidOutput(    TStC1_XQ) = ( p%NumTStC<1 )
   InvalidOutput(   TStC1_XQD) = ( p%NumTStC<1 )
   InvalidOutput(    TStC1_YQ) = ( p%NumTStC<1 )
   InvalidOutput(   TStC1_YQD) = ( p%NumTStC<1 )
   InvalidOutput(    TStC1_ZQ) = ( p%NumTStC<1 )
   InvalidOutput(   TStC1_ZQD) = ( p%NumTStC<1 )
   InvalidOutput(   TStC1_Fxi) = ( p%NumTStC<1 )
   InvalidOutput(   TStC1_Fyi) = ( p%NumTStC<1 )
   InvalidOutput(   TStC1_Fzi) = ( p%NumTStC<1 )
   InvalidOutput(   TStC1_Mxi) = ( p%NumTStC<1 )
   InvalidOutput(   TStC1_Myi) = ( p%NumTStC<1 )
   InvalidOutput(   TStC1_Mzi) = ( p%NumTStC<1 )
   InvalidOutput(   TStC1_Fxl) = ( p%NumTStC<1 )
   InvalidOutput(   TStC1_Fyl) = ( p%NumTStC<1 )
   InvalidOutput(   TStC1_Fzl) = ( p%NumTStC<1 )
   InvalidOutput(   TStC1_Mxl) = ( p%NumTStC<1 )
   InvalidOutput(   TStC1_Myl) = ( p%NumTStC<1 )
   InvalidOutput(   TStC1_Mzl) = ( p%NumTStC<1 )
   InvalidOutput(    TStC2_XQ) = ( p%NumTStC<2 )
   InvalidOutput(   TStC2_XQD) = ( p%NumTStC<2 )
   InvalidOutput(    TStC2_YQ) = ( p%NumTStC<2 )
   InvalidOutput(   TStC2_YQD) = ( p%NumTStC<2 )
   InvalidOutput(    TStC2_ZQ) = ( p%NumTStC<2 )
   InvalidOutput(   TStC2_ZQD) = ( p%NumTStC<2 )
   InvalidOutput(   TStC2_Fxi) = ( p%NumTStC<2 )
   InvalidOutput(   TStC2_Fyi) = ( p%NumTStC<2 )
   InvalidOutput(   TStC2_Fzi) = ( p%NumTStC<2 )
   InvalidOutput(   TStC2_Mxi) = ( p%NumTStC<2 )
   InvalidOutput(   TStC2_Myi) = ( p%NumTStC<2 )
   InvalidOutput(   TStC2_Mzi) = ( p%NumTStC<2 )
   InvalidOutput(   TStC2_Fxl) = ( p%NumTStC<2 )
   InvalidOutput(   TStC2_Fyl) = ( p%NumTStC<2 )
   InvalidOutput(   TStC2_Fzl) = ( p%NumTStC<2 )
   InvalidOutput(   TStC2_Mxl) = ( p%NumTStC<2 )
   InvalidOutput(   TStC2_Myl) = ( p%NumTStC<2 )
   InvalidOutput(   TStC2_Mzl) = ( p%NumTStC<2 )
   InvalidOutput(    TStC3_XQ) = ( p%NumTStC<3 )
   InvalidOutput(   TStC3_XQD) = ( p%NumTStC<3 )
   InvalidOutput(    TStC3_YQ) = ( p%NumTStC<3 )
   InvalidOutput(   TStC3_YQD) = ( p%NumTStC<3 )
   InvalidOutput(    TStC3_ZQ) = ( p%NumTStC<3 )
   InvalidOutput(   TStC3_ZQD) = ( p%NumTStC<3 )
   InvalidOutput(   TStC3_Fxi) = ( p%NumTStC<3 )
   InvalidOutput(   TStC3_Fyi) = ( p%NumTStC<3 )
   InvalidOutput(   TStC3_Fzi) = ( p%NumTStC<3 )
   InvalidOutput(   TStC3_Mxi) = ( p%NumTStC<3 )
   InvalidOutput(   TStC3_Myi) = ( p%NumTStC<3 )
   InvalidOutput(   TStC3_Mzi) = ( p%NumTStC<3 )
   InvalidOutput(   TStC3_Fxl) = ( p%NumTStC<3 )
   InvalidOutput(   TStC3_Fyl) = ( p%NumTStC<3 )
   InvalidOutput(   TStC3_Fzl) = ( p%NumTStC<3 )
   InvalidOutput(   TStC3_Mxl) = ( p%NumTStC<3 )
   InvalidOutput(   TStC3_Myl) = ( p%NumTStC<3 )
   InvalidOutput(   TStC3_Mzl) = ( p%NumTStC<3 )
   InvalidOutput(    TStC4_XQ) = ( p%NumTStC<4 )
   InvalidOutput(   TStC4_XQD) = ( p%NumTStC<4 )
   InvalidOutput(    TStC4_YQ) = ( p%NumTStC<4 )
   InvalidOutput(   TStC4_YQD) = ( p%NumTStC<4 )
   InvalidOutput(    TStC4_ZQ) = ( p%NumTStC<4 )
   InvalidOutput(   TStC4_ZQD) = ( p%NumTStC<4 )
   InvalidOutput(   TStC4_Fxi) = ( p%NumTStC<4 )
   InvalidOutput(   TStC4_Fyi) = ( p%NumTStC<4 )
   InvalidOutput(   TStC4_Fzi) = ( p%NumTStC<4 )
   InvalidOutput(   TStC4_Mxi) = ( p%NumTStC<4 )
   InvalidOutput(   TStC4_Myi) = ( p%NumTStC<4 )
   InvalidOutput(   TStC4_Mzi) = ( p%NumTStC<4 )
   InvalidOutput(   TStC4_Fxl) = ( p%NumTStC<4 )
   InvalidOutput(   TStC4_Fyl) = ( p%NumTStC<4 )
   InvalidOutput(   TStC4_Fzl) = ( p%NumTStC<4 )
   InvalidOutput(   TStC4_Mxl) = ( p%NumTStC<4 )
   InvalidOutput(   TStC4_Myl) = ( p%NumTStC<4 )
   InvalidOutput(   TStC4_Mzl) = ( p%NumTStC<4 )
   InvalidOutput( BStC1_B1_XQ) = ( p%NumBStC<1 .or. p%NumBl<1 )
   InvalidOutput(BStC1_B1_XQD) = ( p%NumBStC<1 .or. p%NumBl<1 )
   InvalidOutput( BStC1_B1_YQ) = ( p%NumBStC<1 .or. p%NumBl<1 )
   InvalidOutput(BStC1_B1_YQD) = ( p%NumBStC<1 .or. p%NumBl<1 )
   InvalidOutput( BStC1_B1_ZQ) = ( p%NumBStC<1 .or. p%NumBl<1 )
   InvalidOutput(BStC1_B1_ZQD) = ( p%NumBStC<1 .or. p%NumBl<1 )
   InvalidOutput(BStC1_B1_Fxi) = ( p%NumBStC<1 .or. p%NumBl<1 )
   InvalidOutput(BStC1_B1_Fyi) = ( p%NumBStC<1 .or. p%NumBl<1 )
   InvalidOutput(BStC1_B1_Fzi) = ( p%NumBStC<1 .or. p%NumBl<1 )
   InvalidOutput(BStC1_B1_Mxi) = ( p%NumBStC<1 .or. p%NumBl<1 )
   InvalidOutput(BStC1_B1_Myi) = ( p%NumBStC<1 .or. p%NumBl<1 )
   InvalidOutput(BStC1_B1_Mzi) = ( p%NumBStC<1 .or. p%NumBl<1 )
   InvalidOutput(BStC1_B1_Fxl) = ( p%NumBStC<1 .or. p%NumBl<1 )
   InvalidOutput(BStC1_B1_Fyl) = ( p%NumBStC<1 .or. p%NumBl<1 )
   InvalidOutput(BStC1_B1_Fzl) = ( p%NumBStC<1 .or. p%NumBl<1 )
   InvalidOutput(BStC1_B1_Mxl) = ( p%NumBStC<1 .or. p%NumBl<1 )
   InvalidOutput(BStC1_B1_Myl) = ( p%NumBStC<1 .or. p%NumBl<1 )
   InvalidOutput(BStC1_B1_Mzl) = ( p%NumBStC<1 .or. p%NumBl<1 )
   InvalidOutput( BStC2_B1_XQ) = ( p%NumBStC<2 .or. p%NumBl<1 )
   InvalidOutput(BStC2_B1_XQD) = ( p%NumBStC<2 .or. p%NumBl<1 )
   InvalidOutput( BStC2_B1_YQ) = ( p%NumBStC<2 .or. p%NumBl<1 )
   InvalidOutput(BStC2_B1_YQD) = ( p%NumBStC<2 .or. p%NumBl<1 )
   InvalidOutput( BStC2_B1_ZQ) = ( p%NumBStC<2 .or. p%NumBl<1 )
   InvalidOutput(BStC2_B1_ZQD) = ( p%NumBStC<2 .or. p%NumBl<1 )
   InvalidOutput(BStC2_B1_Fxi) = ( p%NumBStC<2 .or. p%NumBl<1 )
   InvalidOutput(BStC2_B1_Fyi) = ( p%NumBStC<2 .or. p%NumBl<1 )
   InvalidOutput(BStC2_B1_Fzi) = ( p%NumBStC<2 .or. p%NumBl<1 )
   InvalidOutput(BStC2_B1_Mxi) = ( p%NumBStC<2 .or. p%NumBl<1 )
   InvalidOutput(BStC2_B1_Myi) = ( p%NumBStC<2 .or. p%NumBl<1 )
   InvalidOutput(BStC2_B1_Mzi) = ( p%NumBStC<2 .or. p%NumBl<1 )
   InvalidOutput(BStC2_B1_Fxl) = ( p%NumBStC<2 .or. p%NumBl<1 )
   InvalidOutput(BStC2_B1_Fyl) = ( p%NumBStC<2 .or. p%NumBl<1 )
   InvalidOutput(BStC2_B1_Fzl) = ( p%NumBStC<2 .or. p%NumBl<1 )
   InvalidOutput(BStC2_B1_Mxl) = ( p%NumBStC<2 .or. p%NumBl<1 )
   InvalidOutput(BStC2_B1_Myl) = ( p%NumBStC<2 .or. p%NumBl<1 )
   InvalidOutput(BStC2_B1_Mzl) = ( p%NumBStC<2 .or. p%NumBl<1 )
   InvalidOutput( BStC3_B1_XQ) = ( p%NumBStC<3 .or. p%NumBl<1 )
   InvalidOutput(BStC3_B1_XQD) = ( p%NumBStC<3 .or. p%NumBl<1 )
   InvalidOutput( BStC3_B1_YQ) = ( p%NumBStC<3 .or. p%NumBl<1 )
   InvalidOutput(BStC3_B1_YQD) = ( p%NumBStC<3 .or. p%NumBl<1 )
   InvalidOutput( BStC3_B1_ZQ) = ( p%NumBStC<3 .or. p%NumBl<1 )
   InvalidOutput(BStC3_B1_ZQD) = ( p%NumBStC<3 .or. p%NumBl<1 )
   InvalidOutput(BStC3_B1_Fxi) = ( p%NumBStC<3 .or. p%NumBl<1 )
   InvalidOutput(BStC3_B1_Fyi) = ( p%NumBStC<3 .or. p%NumBl<1 )
   InvalidOutput(BStC3_B1_Fzi) = ( p%NumBStC<3 .or. p%NumBl<1 )
   InvalidOutput(BStC3_B1_Mxi) = ( p%NumBStC<3 .or. p%NumBl<1 )
   InvalidOutput(BStC3_B1_Myi) = ( p%NumBStC<3 .or. p%NumBl<1 )
   InvalidOutput(BStC3_B1_Mzi) = ( p%NumBStC<3 .or. p%NumBl<1 )
   InvalidOutput(BStC3_B1_Fxl) = ( p%NumBStC<3 .or. p%NumBl<1 )
   InvalidOutput(BStC3_B1_Fyl) = ( p%NumBStC<3 .or. p%NumBl<1 )
   InvalidOutput(BStC3_B1_Fzl) = ( p%NumBStC<3 .or. p%NumBl<1 )
   InvalidOutput(BStC3_B1_Mxl) = ( p%NumBStC<3 .or. p%NumBl<1 )
   InvalidOutput(BStC3_B1_Myl) = ( p%NumBStC<3 .or. p%NumBl<1 )
   InvalidOutput(BStC3_B1_Mzl) = ( p%NumBStC<3 .or. p%NumBl<1 )
   InvalidOutput( BStC4_B1_XQ) = ( p%NumBStC<4 .or. p%NumBl<1 )
   InvalidOutput(BStC4_B1_XQD) = ( p%NumBStC<4 .or. p%NumBl<1 )
   InvalidOutput( BStC4_B1_YQ) = ( p%NumBStC<4 .or. p%NumBl<1 )
   InvalidOutput(BStC4_B1_YQD) = ( p%NumBStC<4 .or. p%NumBl<1 )
   InvalidOutput( BStC4_B1_ZQ) = ( p%NumBStC<4 .or. p%NumBl<1 )
   InvalidOutput(BStC4_B1_ZQD) = ( p%NumBStC<4 .or. p%NumBl<1 )
   InvalidOutput(BStC4_B1_Fxi) = ( p%NumBStC<4 .or. p%NumBl<1 )
   InvalidOutput(BStC4_B1_Fyi) = ( p%NumBStC<4 .or. p%NumBl<1 )
   InvalidOutput(BStC4_B1_Fzi) = ( p%NumBStC<4 .or. p%NumBl<1 )
   InvalidOutput(BStC4_B1_Mxi) = ( p%NumBStC<4 .or. p%NumBl<1 )
   InvalidOutput(BStC4_B1_Myi) = ( p%NumBStC<4 .or. p%NumBl<1 )
   InvalidOutput(BStC4_B1_Mzi) = ( p%NumBStC<4 .or. p%NumBl<1 )
   InvalidOutput(BStC4_B1_Fxl) = ( p%NumBStC<4 .or. p%NumBl<1 )
   InvalidOutput(BStC4_B1_Fyl) = ( p%NumBStC<4 .or. p%NumBl<1 )
   InvalidOutput(BStC4_B1_Fzl) = ( p%NumBStC<4 .or. p%NumBl<1 )
   InvalidOutput(BStC4_B1_Mxl) = ( p%NumBStC<4 .or. p%NumBl<1 )
   InvalidOutput(BStC4_B1_Myl) = ( p%NumBStC<4 .or. p%NumBl<1 )
   InvalidOutput(BStC4_B1_Mzl) = ( p%NumBStC<4 .or. p%NumBl<1 )
   InvalidOutput( BStC1_B2_XQ) = ( p%NumBStC<1 .or. p%NumBl<2 )
   InvalidOutput(BStC1_B2_XQD) = ( p%NumBStC<1 .or. p%NumBl<2 )
   InvalidOutput( BStC1_B2_YQ) = ( p%NumBStC<1 .or. p%NumBl<2 )
   InvalidOutput(BStC1_B2_YQD) = ( p%NumBStC<1 .or. p%NumBl<2 )
   InvalidOutput( BStC1_B2_ZQ) = ( p%NumBStC<1 .or. p%NumBl<2 )
   InvalidOutput(BStC1_B2_ZQD) = ( p%NumBStC<1 .or. p%NumBl<2 )
   InvalidOutput(BStC1_B2_Fxi) = ( p%NumBStC<1 .or. p%NumBl<2 )
   InvalidOutput(BStC1_B2_Fyi) = ( p%NumBStC<1 .or. p%NumBl<2 )
   InvalidOutput(BStC1_B2_Fzi) = ( p%NumBStC<1 .or. p%NumBl<2 )
   InvalidOutput(BStC1_B2_Mxi) = ( p%NumBStC<1 .or. p%NumBl<2 )
   InvalidOutput(BStC1_B2_Myi) = ( p%NumBStC<1 .or. p%NumBl<2 )
   InvalidOutput(BStC1_B2_Mzi) = ( p%NumBStC<1 .or. p%NumBl<2 )
   InvalidOutput(BStC1_B2_Fxl) = ( p%NumBStC<1 .or. p%NumBl<2 )
   InvalidOutput(BStC1_B2_Fyl) = ( p%NumBStC<1 .or. p%NumBl<2 )
   InvalidOutput(BStC1_B2_Fzl) = ( p%NumBStC<1 .or. p%NumBl<2 )
   InvalidOutput(BStC1_B2_Mxl) = ( p%NumBStC<1 .or. p%NumBl<2 )
   InvalidOutput(BStC1_B2_Myl) = ( p%NumBStC<1 .or. p%NumBl<2 )
   InvalidOutput(BStC1_B2_Mzl) = ( p%NumBStC<1 .or. p%NumBl<2 )
   InvalidOutput( BStC2_B2_XQ) = ( p%NumBStC<2 .or. p%NumBl<2 )
   InvalidOutput(BStC2_B2_XQD) = ( p%NumBStC<2 .or. p%NumBl<2 )
   InvalidOutput( BStC2_B2_YQ) = ( p%NumBStC<2 .or. p%NumBl<2 )
   InvalidOutput(BStC2_B2_YQD) = ( p%NumBStC<2 .or. p%NumBl<2 )
   InvalidOutput( BStC2_B2_ZQ) = ( p%NumBStC<2 .or. p%NumBl<2 )
   InvalidOutput(BStC2_B2_ZQD) = ( p%NumBStC<2 .or. p%NumBl<2 )
   InvalidOutput(BStC2_B2_Fxi) = ( p%NumBStC<2 .or. p%NumBl<2 )
   InvalidOutput(BStC2_B2_Fyi) = ( p%NumBStC<2 .or. p%NumBl<2 )
   InvalidOutput(BStC2_B2_Fzi) = ( p%NumBStC<2 .or. p%NumBl<2 )
   InvalidOutput(BStC2_B2_Mxi) = ( p%NumBStC<2 .or. p%NumBl<2 )
   InvalidOutput(BStC2_B2_Myi) = ( p%NumBStC<2 .or. p%NumBl<2 )
   InvalidOutput(BStC2_B2_Mzi) = ( p%NumBStC<2 .or. p%NumBl<2 )
   InvalidOutput(BStC2_B2_Fxl) = ( p%NumBStC<2 .or. p%NumBl<2 )
   InvalidOutput(BStC2_B2_Fyl) = ( p%NumBStC<2 .or. p%NumBl<2 )
   InvalidOutput(BStC2_B2_Fzl) = ( p%NumBStC<2 .or. p%NumBl<2 )
   InvalidOutput(BStC2_B2_Mxl) = ( p%NumBStC<2 .or. p%NumBl<2 )
   InvalidOutput(BStC2_B2_Myl) = ( p%NumBStC<2 .or. p%NumBl<2 )
   InvalidOutput(BStC2_B2_Mzl) = ( p%NumBStC<2 .or. p%NumBl<2 )
   InvalidOutput( BStC3_B2_XQ) = ( p%NumBStC<3 .or. p%NumBl<2 )
   InvalidOutput(BStC3_B2_XQD) = ( p%NumBStC<3 .or. p%NumBl<2 )
   InvalidOutput( BStC3_B2_YQ) = ( p%NumBStC<3 .or. p%NumBl<2 )
   InvalidOutput(BStC3_B2_YQD) = ( p%NumBStC<3 .or. p%NumBl<2 )
   InvalidOutput( BStC3_B2_ZQ) = ( p%NumBStC<3 .or. p%NumBl<2 )
   InvalidOutput(BStC3_B2_ZQD) = ( p%NumBStC<3 .or. p%NumBl<2 )
   InvalidOutput(BStC3_B2_Fxi) = ( p%NumBStC<3 .or. p%NumBl<2 )
   InvalidOutput(BStC3_B2_Fyi) = ( p%NumBStC<3 .or. p%NumBl<2 )
   InvalidOutput(BStC3_B2_Fzi) = ( p%NumBStC<3 .or. p%NumBl<2 )
   InvalidOutput(BStC3_B2_Mxi) = ( p%NumBStC<3 .or. p%NumBl<2 )
   InvalidOutput(BStC3_B2_Myi) = ( p%NumBStC<3 .or. p%NumBl<2 )
   InvalidOutput(BStC3_B2_Mzi) = ( p%NumBStC<3 .or. p%NumBl<2 )
   InvalidOutput(BStC3_B2_Fxl) = ( p%NumBStC<3 .or. p%NumBl<2 )
   InvalidOutput(BStC3_B2_Fyl) = ( p%NumBStC<3 .or. p%NumBl<2 )
   InvalidOutput(BStC3_B2_Fzl) = ( p%NumBStC<3 .or. p%NumBl<2 )
   InvalidOutput(BStC3_B2_Mxl) = ( p%NumBStC<3 .or. p%NumBl<2 )
   InvalidOutput(BStC3_B2_Myl) = ( p%NumBStC<3 .or. p%NumBl<2 )
   InvalidOutput(BStC3_B2_Mzl) = ( p%NumBStC<3 .or. p%NumBl<2 )
   InvalidOutput( BStC4_B2_XQ) = ( p%NumBStC<4 .or. p%NumBl<2 )
   InvalidOutput(BStC4_B2_XQD) = ( p%NumBStC<4 .or. p%NumBl<2 )
   InvalidOutput( BStC4_B2_YQ) = ( p%NumBStC<4 .or. p%NumBl<2 )
   InvalidOutput(BStC4_B2_YQD) = ( p%NumBStC<4 .or. p%NumBl<2 )
   InvalidOutput( BStC4_B2_ZQ) = ( p%NumBStC<4 .or. p%NumBl<2 )
   InvalidOutput(BStC4_B2_ZQD) = ( p%NumBStC<4 .or. p%NumBl<2 )
   InvalidOutput(BStC4_B2_Fxi) = ( p%NumBStC<4 .or. p%NumBl<2 )
   InvalidOutput(BStC4_B2_Fyi) = ( p%NumBStC<4 .or. p%NumBl<2 )
   InvalidOutput(BStC4_B2_Fzi) = ( p%NumBStC<4 .or. p%NumBl<2 )
   InvalidOutput(BStC4_B2_Mxi) = ( p%NumBStC<4 .or. p%NumBl<2 )
   InvalidOutput(BStC4_B2_Myi) = ( p%NumBStC<4 .or. p%NumBl<2 )
   InvalidOutput(BStC4_B2_Mzi) = ( p%NumBStC<4 .or. p%NumBl<2 )
   InvalidOutput(BStC4_B2_Fxl) = ( p%NumBStC<4 .or. p%NumBl<2 )
   InvalidOutput(BStC4_B2_Fyl) = ( p%NumBStC<4 .or. p%NumBl<2 )
   InvalidOutput(BStC4_B2_Fzl) = ( p%NumBStC<4 .or. p%NumBl<2 )
   InvalidOutput(BStC4_B2_Mxl) = ( p%NumBStC<4 .or. p%NumBl<2 )
   InvalidOutput(BStC4_B2_Myl) = ( p%NumBStC<4 .or. p%NumBl<2 )
   InvalidOutput(BStC4_B2_Mzl) = ( p%NumBStC<4 .or. p%NumBl<2 )
   InvalidOutput( BStC1_B3_XQ) = ( p%NumBStC<1 .or. p%NumBl<3 )
   InvalidOutput(BStC1_B3_XQD) = ( p%NumBStC<1 .or. p%NumBl<3 )
   InvalidOutput( BStC1_B3_YQ) = ( p%NumBStC<1 .or. p%NumBl<3 )
   InvalidOutput(BStC1_B3_YQD) = ( p%NumBStC<1 .or. p%NumBl<3 )
   InvalidOutput( BStC1_B3_ZQ) = ( p%NumBStC<1 .or. p%NumBl<3 )
   InvalidOutput(BStC1_B3_ZQD) = ( p%NumBStC<1 .or. p%NumBl<3 )
   InvalidOutput(BStC1_B3_Fxi) = ( p%NumBStC<1 .or. p%NumBl<3 )
   InvalidOutput(BStC1_B3_Fyi) = ( p%NumBStC<1 .or. p%NumBl<3 )
   InvalidOutput(BStC1_B3_Fzi) = ( p%NumBStC<1 .or. p%NumBl<3 )
   InvalidOutput(BStC1_B3_Mxi) = ( p%NumBStC<1 .or. p%NumBl<3 )
   InvalidOutput(BStC1_B3_Myi) = ( p%NumBStC<1 .or. p%NumBl<3 )
   InvalidOutput(BStC1_B3_Mzi) = ( p%NumBStC<1 .or. p%NumBl<3 )
   InvalidOutput(BStC1_B3_Fxl) = ( p%NumBStC<1 .or. p%NumBl<3 )
   InvalidOutput(BStC1_B3_Fyl) = ( p%NumBStC<1 .or. p%NumBl<3 )
   InvalidOutput(BStC1_B3_Fzl) = ( p%NumBStC<1 .or. p%NumBl<3 )
   InvalidOutput(BStC1_B3_Mxl) = ( p%NumBStC<1 .or. p%NumBl<3 )
   InvalidOutput(BStC1_B3_Myl) = ( p%NumBStC<1 .or. p%NumBl<3 )
   InvalidOutput(BStC1_B3_Mzl) = ( p%NumBStC<1 .or. p%NumBl<3 )
   InvalidOutput( BStC2_B3_XQ) = ( p%NumBStC<2 .or. p%NumBl<3 )
   InvalidOutput(BStC2_B3_XQD) = ( p%NumBStC<2 .or. p%NumBl<3 )
   InvalidOutput( BStC2_B3_YQ) = ( p%NumBStC<2 .or. p%NumBl<3 )
   InvalidOutput(BStC2_B3_YQD) = ( p%NumBStC<2 .or. p%NumBl<3 )
   InvalidOutput( BStC2_B3_ZQ) = ( p%NumBStC<2 .or. p%NumBl<3 )
   InvalidOutput(BStC2_B3_ZQD) = ( p%NumBStC<2 .or. p%NumBl<3 )
   InvalidOutput(BStC2_B3_Fxi) = ( p%NumBStC<2 .or. p%NumBl<3 )
   InvalidOutput(BStC2_B3_Fyi) = ( p%NumBStC<2 .or. p%NumBl<3 )
   InvalidOutput(BStC2_B3_Fzi) = ( p%NumBStC<2 .or. p%NumBl<3 )
   InvalidOutput(BStC2_B3_Mxi) = ( p%NumBStC<2 .or. p%NumBl<3 )
   InvalidOutput(BStC2_B3_Myi) = ( p%NumBStC<2 .or. p%NumBl<3 )
   InvalidOutput(BStC2_B3_Mzi) = ( p%NumBStC<2 .or. p%NumBl<3 )
   InvalidOutput(BStC2_B3_Fxl) = ( p%NumBStC<2 .or. p%NumBl<3 )
   InvalidOutput(BStC2_B3_Fyl) = ( p%NumBStC<2 .or. p%NumBl<3 )
   InvalidOutput(BStC2_B3_Fzl) = ( p%NumBStC<2 .or. p%NumBl<3 )
   InvalidOutput(BStC2_B3_Mxl) = ( p%NumBStC<2 .or. p%NumBl<3 )
   InvalidOutput(BStC2_B3_Myl) = ( p%NumBStC<2 .or. p%NumBl<3 )
   InvalidOutput(BStC2_B3_Mzl) = ( p%NumBStC<2 .or. p%NumBl<3 )
   InvalidOutput( BStC3_B3_XQ) = ( p%NumBStC<3 .or. p%NumBl<3 )
   InvalidOutput(BStC3_B3_XQD) = ( p%NumBStC<3 .or. p%NumBl<3 )
   InvalidOutput( BStC3_B3_YQ) = ( p%NumBStC<3 .or. p%NumBl<3 )
   InvalidOutput(BStC3_B3_YQD) = ( p%NumBStC<3 .or. p%NumBl<3 )
   InvalidOutput( BStC3_B3_ZQ) = ( p%NumBStC<3 .or. p%NumBl<3 )
   InvalidOutput(BStC3_B3_ZQD) = ( p%NumBStC<3 .or. p%NumBl<3 )
   InvalidOutput(BStC3_B3_Fxi) = ( p%NumBStC<3 .or. p%NumBl<3 )
   InvalidOutput(BStC3_B3_Fyi) = ( p%NumBStC<3 .or. p%NumBl<3 )
   InvalidOutput(BStC3_B3_Fzi) = ( p%NumBStC<3 .or. p%NumBl<3 )
   InvalidOutput(BStC3_B3_Mxi) = ( p%NumBStC<3 .or. p%NumBl<3 )
   InvalidOutput(BStC3_B3_Myi) = ( p%NumBStC<3 .or. p%NumBl<3 )
   InvalidOutput(BStC3_B3_Mzi) = ( p%NumBStC<3 .or. p%NumBl<3 )
   InvalidOutput(BStC3_B3_Fxl) = ( p%NumBStC<3 .or. p%NumBl<3 )
   InvalidOutput(BStC3_B3_Fyl) = ( p%NumBStC<3 .or. p%NumBl<3 )
   InvalidOutput(BStC3_B3_Fzl) = ( p%NumBStC<3 .or. p%NumBl<3 )
   InvalidOutput(BStC3_B3_Mxl) = ( p%NumBStC<3 .or. p%NumBl<3 )
   InvalidOutput(BStC3_B3_Myl) = ( p%NumBStC<3 .or. p%NumBl<3 )
   InvalidOutput(BStC3_B3_Mzl) = ( p%NumBStC<3 .or. p%NumBl<3 )
   InvalidOutput( BStC4_B3_XQ) = ( p%NumBStC<4 .or. p%NumBl<3 )
   InvalidOutput(BStC4_B3_XQD) = ( p%NumBStC<4 .or. p%NumBl<3 )
   InvalidOutput( BStC4_B3_YQ) = ( p%NumBStC<4 .or. p%NumBl<3 )
   InvalidOutput(BStC4_B3_YQD) = ( p%NumBStC<4 .or. p%NumBl<3 )
   InvalidOutput( BStC4_B3_ZQ) = ( p%NumBStC<4 .or. p%NumBl<3 )
   InvalidOutput(BStC4_B3_ZQD) = ( p%NumBStC<4 .or. p%NumBl<3 )
   InvalidOutput(BStC4_B3_Fxi) = ( p%NumBStC<4 .or. p%NumBl<3 )
   InvalidOutput(BStC4_B3_Fyi) = ( p%NumBStC<4 .or. p%NumBl<3 )
   InvalidOutput(BStC4_B3_Fzi) = ( p%NumBStC<4 .or. p%NumBl<3 )
   InvalidOutput(BStC4_B3_Mxi) = ( p%NumBStC<4 .or. p%NumBl<3 )
   InvalidOutput(BStC4_B3_Myi) = ( p%NumBStC<4 .or. p%NumBl<3 )
   InvalidOutput(BStC4_B3_Mzi) = ( p%NumBStC<4 .or. p%NumBl<3 )
   InvalidOutput(BStC4_B3_Fxl) = ( p%NumBStC<4 .or. p%NumBl<3 )
   InvalidOutput(BStC4_B3_Fyl) = ( p%NumBStC<4 .or. p%NumBl<3 )
   InvalidOutput(BStC4_B3_Fzl) = ( p%NumBStC<4 .or. p%NumBl<3 )
   InvalidOutput(BStC4_B3_Mxl) = ( p%NumBStC<4 .or. p%NumBl<3 )
   InvalidOutput(BStC4_B3_Myl) = ( p%NumBStC<4 .or. p%NumBl<3 )
   InvalidOutput(BStC4_B3_Mzl) = ( p%NumBStC<4 .or. p%NumBl<3 )
   InvalidOutput( BStC1_B4_XQ) = ( p%NumBStC<1 .or. p%NumBl<4 )
   InvalidOutput(BStC1_B4_XQD) = ( p%NumBStC<1 .or. p%NumBl<4 )
   InvalidOutput( BStC1_B4_YQ) = ( p%NumBStC<1 .or. p%NumBl<4 )
   InvalidOutput(BStC1_B4_YQD) = ( p%NumBStC<1 .or. p%NumBl<4 )
   InvalidOutput( BStC1_B4_ZQ) = ( p%NumBStC<1 .or. p%NumBl<4 )
   InvalidOutput(BStC1_B4_ZQD) = ( p%NumBStC<1 .or. p%NumBl<4 )
   InvalidOutput(BStC1_B4_Fxi) = ( p%NumBStC<1 .or. p%NumBl<4 )
   InvalidOutput(BStC1_B4_Fyi) = ( p%NumBStC<1 .or. p%NumBl<4 )
   InvalidOutput(BStC1_B4_Fzi) = ( p%NumBStC<1 .or. p%NumBl<4 )
   InvalidOutput(BStC1_B4_Mxi) = ( p%NumBStC<1 .or. p%NumBl<4 )
   InvalidOutput(BStC1_B4_Myi) = ( p%NumBStC<1 .or. p%NumBl<4 )
   InvalidOutput(BStC1_B4_Mzi) = ( p%NumBStC<1 .or. p%NumBl<4 )
   InvalidOutput(BStC1_B4_Fxl) = ( p%NumBStC<1 .or. p%NumBl<4 )
   InvalidOutput(BStC1_B4_Fyl) = ( p%NumBStC<1 .or. p%NumBl<4 )
   InvalidOutput(BStC1_B4_Fzl) = ( p%NumBStC<1 .or. p%NumBl<4 )
   InvalidOutput(BStC1_B4_Mxl) = ( p%NumBStC<1 .or. p%NumBl<4 )
   InvalidOutput(BStC1_B4_Myl) = ( p%NumBStC<1 .or. p%NumBl<4 )
   InvalidOutput(BStC1_B4_Mzl) = ( p%NumBStC<1 .or. p%NumBl<4 )
   InvalidOutput( BStC2_B4_XQ) = ( p%NumBStC<2 .or. p%NumBl<4 )
   InvalidOutput(BStC2_B4_XQD) = ( p%NumBStC<2 .or. p%NumBl<4 )
   InvalidOutput( BStC2_B4_YQ) = ( p%NumBStC<2 .or. p%NumBl<4 )
   InvalidOutput(BStC2_B4_YQD) = ( p%NumBStC<2 .or. p%NumBl<4 )
   InvalidOutput( BStC2_B4_ZQ) = ( p%NumBStC<2 .or. p%NumBl<4 )
   InvalidOutput(BStC2_B4_ZQD) = ( p%NumBStC<2 .or. p%NumBl<4 )
   InvalidOutput(BStC2_B4_Fxi) = ( p%NumBStC<2 .or. p%NumBl<4 )
   InvalidOutput(BStC2_B4_Fyi) = ( p%NumBStC<2 .or. p%NumBl<4 )
   InvalidOutput(BStC2_B4_Fzi) = ( p%NumBStC<2 .or. p%NumBl<4 )
   InvalidOutput(BStC2_B4_Mxi) = ( p%NumBStC<2 .or. p%NumBl<4 )
   InvalidOutput(BStC2_B4_Myi) = ( p%NumBStC<2 .or. p%NumBl<4 )
   InvalidOutput(BStC2_B4_Mzi) = ( p%NumBStC<2 .or. p%NumBl<4 )
   InvalidOutput(BStC2_B4_Fxl) = ( p%NumBStC<2 .or. p%NumBl<4 )
   InvalidOutput(BStC2_B4_Fyl) = ( p%NumBStC<2 .or. p%NumBl<4 )
   InvalidOutput(BStC2_B4_Fzl) = ( p%NumBStC<2 .or. p%NumBl<4 )
   InvalidOutput(BStC2_B4_Mxl) = ( p%NumBStC<2 .or. p%NumBl<4 )
   InvalidOutput(BStC2_B4_Myl) = ( p%NumBStC<2 .or. p%NumBl<4 )
   InvalidOutput(BStC2_B4_Mzl) = ( p%NumBStC<2 .or. p%NumBl<4 )
   InvalidOutput( BStC3_B4_XQ) = ( p%NumBStC<3 .or. p%NumBl<4 )
   InvalidOutput(BStC3_B4_XQD) = ( p%NumBStC<3 .or. p%NumBl<4 )
   InvalidOutput( BStC3_B4_YQ) = ( p%NumBStC<3 .or. p%NumBl<4 )
   InvalidOutput(BStC3_B4_YQD) = ( p%NumBStC<3 .or. p%NumBl<4 )
   InvalidOutput( BStC3_B4_ZQ) = ( p%NumBStC<3 .or. p%NumBl<4 )
   InvalidOutput(BStC3_B4_ZQD) = ( p%NumBStC<3 .or. p%NumBl<4 )
   InvalidOutput(BStC3_B4_Fxi) = ( p%NumBStC<3 .or. p%NumBl<4 )
   InvalidOutput(BStC3_B4_Fyi) = ( p%NumBStC<3 .or. p%NumBl<4 )
   InvalidOutput(BStC3_B4_Fzi) = ( p%NumBStC<3 .or. p%NumBl<4 )
   InvalidOutput(BStC3_B4_Mxi) = ( p%NumBStC<3 .or. p%NumBl<4 )
   InvalidOutput(BStC3_B4_Myi) = ( p%NumBStC<3 .or. p%NumBl<4 )
   InvalidOutput(BStC3_B4_Mzi) = ( p%NumBStC<3 .or. p%NumBl<4 )
   InvalidOutput(BStC3_B4_Fxl) = ( p%NumBStC<3 .or. p%NumBl<4 )
   InvalidOutput(BStC3_B4_Fyl) = ( p%NumBStC<3 .or. p%NumBl<4 )
   InvalidOutput(BStC3_B4_Fzl) = ( p%NumBStC<3 .or. p%NumBl<4 )
   InvalidOutput(BStC3_B4_Mxl) = ( p%NumBStC<3 .or. p%NumBl<4 )
   InvalidOutput(BStC3_B4_Myl) = ( p%NumBStC<3 .or. p%NumBl<4 )
   InvalidOutput(BStC3_B4_Mzl) = ( p%NumBStC<3 .or. p%NumBl<4 )
   InvalidOutput( BStC4_B4_XQ) = ( p%NumBStC<4 .or. p%NumBl<4 )
   InvalidOutput(BStC4_B4_XQD) = ( p%NumBStC<4 .or. p%NumBl<4 )
   InvalidOutput( BStC4_B4_YQ) = ( p%NumBStC<4 .or. p%NumBl<4 )
   InvalidOutput(BStC4_B4_YQD) = ( p%NumBStC<4 .or. p%NumBl<4 )
   InvalidOutput( BStC4_B4_ZQ) = ( p%NumBStC<4 .or. p%NumBl<4 )
   InvalidOutput(BStC4_B4_ZQD) = ( p%NumBStC<4 .or. p%NumBl<4 )
   InvalidOutput(BStC4_B4_Fxi) = ( p%NumBStC<4 .or. p%NumBl<4 )
   InvalidOutput(BStC4_B4_Fyi) = ( p%NumBStC<4 .or. p%NumBl<4 )
   InvalidOutput(BStC4_B4_Fzi) = ( p%NumBStC<4 .or. p%NumBl<4 )
   InvalidOutput(BStC4_B4_Mxi) = ( p%NumBStC<4 .or. p%NumBl<4 )
   InvalidOutput(BStC4_B4_Myi) = ( p%NumBStC<4 .or. p%NumBl<4 )
   InvalidOutput(BStC4_B4_Mzi) = ( p%NumBStC<4 .or. p%NumBl<4 )
   InvalidOutput(BStC4_B4_Fxl) = ( p%NumBStC<4 .or. p%NumBl<4 )
   InvalidOutput(BStC4_B4_Fyl) = ( p%NumBStC<4 .or. p%NumBl<4 )
   InvalidOutput(BStC4_B4_Fzl) = ( p%NumBStC<4 .or. p%NumBl<4 )
   InvalidOutput(BStC4_B4_Mxl) = ( p%NumBStC<4 .or. p%NumBl<4 )
   InvalidOutput(BStC4_B4_Myl) = ( p%NumBStC<4 .or. p%NumBl<4 )
   InvalidOutput(BStC4_B4_Mzl) = ( p%NumBStC<4 .or. p%NumBl<4 )
   InvalidOutput(    SStC1_XQ) = ( p%NumSStC<1 )
   InvalidOutput(   SStC1_XQD) = ( p%NumSStC<1 )
   InvalidOutput(    SStC1_YQ) = ( p%NumSStC<1 )
   InvalidOutput(   SStC1_YQD) = ( p%NumSStC<1 )
   InvalidOutput(    SStC1_ZQ) = ( p%NumSStC<1 )
   InvalidOutput(   SStC1_ZQD) = ( p%NumSStC<1 )
   InvalidOutput(    SStC1_bQ) = ( p%NumSStC<1 )
   InvalidOutput(   SStC1_bQD) = ( p%NumSStC<1 )
   InvalidOutput(   SStC1_Fxi) = ( p%NumSStC<1 )
   InvalidOutput(   SStC1_Fyi) = ( p%NumSStC<1 )
   InvalidOutput(   SStC1_Fzi) = ( p%NumSStC<1 )
   InvalidOutput(   SStC1_Mxi) = ( p%NumSStC<1 )
   InvalidOutput(   SStC1_Myi) = ( p%NumSStC<1 )
   InvalidOutput(   SStC1_Mzi) = ( p%NumSStC<1 )
   InvalidOutput(   SStC1_Fxl) = ( p%NumSStC<1 )
   InvalidOutput(   SStC1_Fyl) = ( p%NumSStC<1 )
   InvalidOutput(   SStC1_Fzl) = ( p%NumSStC<1 )
   InvalidOutput(   SStC1_Mxl) = ( p%NumSStC<1 )
   InvalidOutput(   SStC1_Myl) = ( p%NumSStC<1 )
   InvalidOutput(   SStC1_Mzl) = ( p%NumSStC<1 )
   InvalidOutput(    SStC2_XQ) = ( p%NumSStC<2 )
   InvalidOutput(   SStC2_XQD) = ( p%NumSStC<2 )
   InvalidOutput(    SStC2_YQ) = ( p%NumSStC<2 )
   InvalidOutput(   SStC2_YQD) = ( p%NumSStC<2 )
   InvalidOutput(    SStC2_ZQ) = ( p%NumSStC<2 )
   InvalidOutput(   SStC2_ZQD) = ( p%NumSStC<2 )
   InvalidOutput(    SStC2_bQ) = ( p%NumSStC<2 )
   InvalidOutput(   SStC2_bQD) = ( p%NumSStC<2 )
   InvalidOutput(   SStC2_Fxi) = ( p%NumSStC<2 )
   InvalidOutput(   SStC2_Fyi) = ( p%NumSStC<2 )
   InvalidOutput(   SStC2_Fzi) = ( p%NumSStC<2 )
   InvalidOutput(   SStC2_Mxi) = ( p%NumSStC<2 )
   InvalidOutput(   SStC2_Myi) = ( p%NumSStC<2 )
   InvalidOutput(   SStC2_Mzi) = ( p%NumSStC<2 )
   InvalidOutput(   SStC2_Fxl) = ( p%NumSStC<2 )
   InvalidOutput(   SStC2_Fyl) = ( p%NumSStC<2 )
   InvalidOutput(   SStC2_Fzl) = ( p%NumSStC<2 )
   InvalidOutput(   SStC2_Mxl) = ( p%NumSStC<2 )
   InvalidOutput(   SStC2_Myl) = ( p%NumSStC<2 )
   InvalidOutput(   SStC2_Mzl) = ( p%NumSStC<2 )
   InvalidOutput(    SStC3_XQ) = ( p%NumSStC<3 )
   InvalidOutput(   SStC3_XQD) = ( p%NumSStC<3 )
   InvalidOutput(    SStC3_YQ) = ( p%NumSStC<3 )
   InvalidOutput(   SStC3_YQD) = ( p%NumSStC<3 )
   InvalidOutput(    SStC3_ZQ) = ( p%NumSStC<3 )
   InvalidOutput(   SStC3_ZQD) = ( p%NumSStC<3 )
   InvalidOutput(    SStC3_bQ) = ( p%NumSStC<3 )
   InvalidOutput(   SStC3_bQD) = ( p%NumSStC<3 )
   InvalidOutput(   SStC3_Fxi) = ( p%NumSStC<3 )
   InvalidOutput(   SStC3_Fyi) = ( p%NumSStC<3 )
   InvalidOutput(   SStC3_Fzi) = ( p%NumSStC<3 )
   InvalidOutput(   SStC3_Mxi) = ( p%NumSStC<3 )
   InvalidOutput(   SStC3_Myi) = ( p%NumSStC<3 )
   InvalidOutput(   SStC3_Mzi) = ( p%NumSStC<3 )
   InvalidOutput(   SStC3_Fxl) = ( p%NumSStC<3 )
   InvalidOutput(   SStC3_Fyl) = ( p%NumSStC<3 )
   InvalidOutput(   SStC3_Fzl) = ( p%NumSStC<3 )
   InvalidOutput(   SStC3_Mxl) = ( p%NumSStC<3 )
   InvalidOutput(   SStC3_Myl) = ( p%NumSStC<3 )
   InvalidOutput(   SStC3_Mzl) = ( p%NumSStC<3 )
   InvalidOutput(    SStC4_XQ) = ( p%NumSStC<4 )
   InvalidOutput(   SStC4_XQD) = ( p%NumSStC<4 )
   InvalidOutput(    SStC4_YQ) = ( p%NumSStC<4 )
   InvalidOutput(   SStC4_YQD) = ( p%NumSStC<4 )
   InvalidOutput(    SStC4_ZQ) = ( p%NumSStC<4 )
   InvalidOutput(   SStC4_ZQD) = ( p%NumSStC<4 )
   InvalidOutput(    SStC4_bQ) = ( p%NumSStC<4 )
   InvalidOutput(   SStC4_bQD) = ( p%NumSStC<4 )
   InvalidOutput(   SStC4_Fxi) = ( p%NumSStC<4 )
   InvalidOutput(   SStC4_Fyi) = ( p%NumSStC<4 )
   InvalidOutput(   SStC4_Fzi) = ( p%NumSStC<4 )
   InvalidOutput(   SStC4_Mxi) = ( p%NumSStC<4 )
   InvalidOutput(   SStC4_Myi) = ( p%NumSStC<4 )
   InvalidOutput(   SStC4_Mzi) = ( p%NumSStC<4 )
   InvalidOutput(   SStC4_Fxl) = ( p%NumSStC<4 )
   InvalidOutput(   SStC4_Fyl) = ( p%NumSStC<4 )
   InvalidOutput(   SStC4_Fzl) = ( p%NumSStC<4 )
   InvalidOutput(   SStC4_Mxl) = ( p%NumSStC<4 )
   InvalidOutput(   SStC4_Myl) = ( p%NumSStC<4 )
   InvalidOutput(   SStC4_Mzl) = ( p%NumSStC<4 )


   !-------------------------------------------------------------------------------------------------
   ! Allocate and set index, name, and units for the output channels
   ! If a selected output channel is not available in this module, set error flag.
   !-------------------------------------------------------------------------------------------------

   ALLOCATE ( p%OutParam(0:p%NumOuts) , STAT=ErrStat2 )
   IF ( ErrStat2 /= 0_IntKi )  THEN
      CALL SetErrStat( ErrID_Fatal,"Error allocating memory for the ServoDyn OutParam array.", ErrStat, ErrMsg, RoutineName )
      RETURN
   ENDIF

      ! Set index, name, and units for the time output channel:

   p%OutParam(0)%Indx  = Time
   p%OutParam(0)%Name  = "Time"    ! OutParam(0) is the time channel by default.
   p%OutParam(0)%Units = "(s)"
   p%OutParam(0)%SignM = 1


      ! Set index, name, and units for all of the output channels.
      ! If a selected output channel is not available by this module set ErrStat = ErrID_Warn.

   DO I = 1,p%NumOuts

      p%OutParam(I)%Name  = OutList(I)

      Indx = FindValidChannelIndx(OutList(I), ValidParamAry, p%OutParam(I)%SignM)

      IF ( Indx > 0 ) THEN ! we found the channel name
         IF ( InvalidOutput( ParamIndxAry(Indx) ) ) THEN  ! but, it isn't valid for these settings
            p%OutParam(I)%Indx  = 0                 ! pick any valid channel (I just picked "Time=0" here because it's universal)
            p%OutParam(I)%Units = "INVALID"
            p%OutParam(I)%SignM = 0
         ELSE
            p%OutParam(I)%Indx  = ParamIndxAry(Indx)
            p%OutParam(I)%Units = ParamUnitsAry(Indx) ! it's a valid output
         END IF
      ELSE ! this channel isn't valid
         p%OutParam(I)%Indx  = 0                    ! pick any valid channel (I just picked "Time=0" here because it's universal)
         p%OutParam(I)%Units = "INVALID"
         p%OutParam(I)%SignM = 0                    ! multiply all results by zero
   
         CALL SetErrStat(ErrID_Fatal, TRIM(p%OutParam(I)%Name)//" is not an available output channel.",ErrStat,ErrMsg,RoutineName)
      END IF
   
   END DO
   
   RETURN
END SUBROUTINE SetOutParam
!----------------------------------------------------------------------------------------------------------------------------------
!End of code generated by Matlab script
!**********************************************************************************************************************************
END MODULE ServoDyn_IO_Params
