! ===================================================================================================
! NOTE: The following lines of code were generated by a Matlab script called "Write_ChckOutLst.m"
!      using the parameters listed in the "OutListParameters.xlsx" Excel file. Any changes to these
!      lines should be modified in the Matlab script and/or Excel worksheet as necessary.
! ===================================================================================================
! This code was generated by "Write_ChckOutLst.m".
MODULE ServoDyn_IO_Params

   USE NWTC_Library
   USE ServoDyn_Types

   IMPLICIT NONE


     ! Indices for computing output channels:
     ! NOTES:
     !    (1) These parameters are in the order stored in "OutListParameters.xlsx"
     !    (2) Array AllOuts() must be dimensioned to the value of the largest output parameter

     !  Time:

   INTEGER(IntKi), PARAMETER      :: Time         =   0


     ! Airfoil control:

   INTEGER(IntKi), PARAMETER      :: BlAirFlC1    =   1
   INTEGER(IntKi), PARAMETER      :: BlAirFlC2    =   2
   INTEGER(IntKi), PARAMETER      :: BlAirFlC3    =   3


     ! Pitch Control:

   INTEGER(IntKi), PARAMETER      :: BlPitchC1    =   4
   INTEGER(IntKi), PARAMETER      :: BlPitchC2    =   5
   INTEGER(IntKi), PARAMETER      :: BlPitchC3    =   6


     ! Generator and Torque Control:

   INTEGER(IntKi), PARAMETER      :: GenTq        =   7
   INTEGER(IntKi), PARAMETER      :: GenPwr       =   8


     ! High Speed Shaft Brake:

   INTEGER(IntKi), PARAMETER      :: HSSBrTqC     =   9


     ! Nacelle Yaw Control:

   INTEGER(IntKi), PARAMETER      :: YawMomCom    =  10


     ! Nacelle Structural Control  (StC):

   INTEGER(IntKi), PARAMETER      :: NStC1_XQ     =  11
   INTEGER(IntKi), PARAMETER      :: NStC1_XQD    =  12
   INTEGER(IntKi), PARAMETER      :: NStC1_YQ     =  13
   INTEGER(IntKi), PARAMETER      :: NStC1_YQD    =  14
   INTEGER(IntKi), PARAMETER      :: NStC1_ZQ     =  15
   INTEGER(IntKi), PARAMETER      :: NStC1_ZQD    =  16
   INTEGER(IntKi), PARAMETER      :: NStC1_Fxi    =  17
   INTEGER(IntKi), PARAMETER      :: NStC1_Fyi    =  18
   INTEGER(IntKi), PARAMETER      :: NStC1_Fzi    =  19
   INTEGER(IntKi), PARAMETER      :: NStC1_Mxi    =  20
   INTEGER(IntKi), PARAMETER      :: NStC1_Myi    =  21
   INTEGER(IntKi), PARAMETER      :: NStC1_Mzi    =  22
   INTEGER(IntKi), PARAMETER      :: NStC1_Fxl    =  23
   INTEGER(IntKi), PARAMETER      :: NStC1_Fyl    =  24
   INTEGER(IntKi), PARAMETER      :: NStC1_Fzl    =  25
   INTEGER(IntKi), PARAMETER      :: NStC1_Mxl    =  26
   INTEGER(IntKi), PARAMETER      :: NStC1_Myl    =  27
   INTEGER(IntKi), PARAMETER      :: NStC1_Mzl    =  28
   INTEGER(IntKi), PARAMETER      :: NStC2_XQ     =  29
   INTEGER(IntKi), PARAMETER      :: NStC2_XQD    =  30
   INTEGER(IntKi), PARAMETER      :: NStC2_YQ     =  31
   INTEGER(IntKi), PARAMETER      :: NStC2_YQD    =  32
   INTEGER(IntKi), PARAMETER      :: NStC2_ZQ     =  33
   INTEGER(IntKi), PARAMETER      :: NStC2_ZQD    =  34
   INTEGER(IntKi), PARAMETER      :: NStC2_Fxi    =  35
   INTEGER(IntKi), PARAMETER      :: NStC2_Fyi    =  36
   INTEGER(IntKi), PARAMETER      :: NStC2_Fzi    =  37
   INTEGER(IntKi), PARAMETER      :: NStC2_Mxi    =  38
   INTEGER(IntKi), PARAMETER      :: NStC2_Myi    =  39
   INTEGER(IntKi), PARAMETER      :: NStC2_Mzi    =  40
   INTEGER(IntKi), PARAMETER      :: NStC2_Fxl    =  41
   INTEGER(IntKi), PARAMETER      :: NStC2_Fyl    =  42
   INTEGER(IntKi), PARAMETER      :: NStC2_Fzl    =  43
   INTEGER(IntKi), PARAMETER      :: NStC2_Mxl    =  44
   INTEGER(IntKi), PARAMETER      :: NStC2_Myl    =  45
   INTEGER(IntKi), PARAMETER      :: NStC2_Mzl    =  46
   INTEGER(IntKi), PARAMETER      :: NStC3_XQ     =  47
   INTEGER(IntKi), PARAMETER      :: NStC3_XQD    =  48
   INTEGER(IntKi), PARAMETER      :: NStC3_YQ     =  49
   INTEGER(IntKi), PARAMETER      :: NStC3_YQD    =  50
   INTEGER(IntKi), PARAMETER      :: NStC3_ZQ     =  51
   INTEGER(IntKi), PARAMETER      :: NStC3_ZQD    =  52
   INTEGER(IntKi), PARAMETER      :: NStC3_Fxi    =  53
   INTEGER(IntKi), PARAMETER      :: NStC3_Fyi    =  54
   INTEGER(IntKi), PARAMETER      :: NStC3_Fzi    =  55
   INTEGER(IntKi), PARAMETER      :: NStC3_Mxi    =  56
   INTEGER(IntKi), PARAMETER      :: NStC3_Myi    =  57
   INTEGER(IntKi), PARAMETER      :: NStC3_Mzi    =  58
   INTEGER(IntKi), PARAMETER      :: NStC3_Fxl    =  59
   INTEGER(IntKi), PARAMETER      :: NStC3_Fyl    =  60
   INTEGER(IntKi), PARAMETER      :: NStC3_Fzl    =  61
   INTEGER(IntKi), PARAMETER      :: NStC3_Mxl    =  62
   INTEGER(IntKi), PARAMETER      :: NStC3_Myl    =  63
   INTEGER(IntKi), PARAMETER      :: NStC3_Mzl    =  64
   INTEGER(IntKi), PARAMETER      :: NStC4_XQ     =  65
   INTEGER(IntKi), PARAMETER      :: NStC4_XQD    =  66
   INTEGER(IntKi), PARAMETER      :: NStC4_YQ     =  67
   INTEGER(IntKi), PARAMETER      :: NStC4_YQD    =  68
   INTEGER(IntKi), PARAMETER      :: NStC4_ZQ     =  69
   INTEGER(IntKi), PARAMETER      :: NStC4_ZQD    =  70
   INTEGER(IntKi), PARAMETER      :: NStC4_Fxi    =  71
   INTEGER(IntKi), PARAMETER      :: NStC4_Fyi    =  72
   INTEGER(IntKi), PARAMETER      :: NStC4_Fzi    =  73
   INTEGER(IntKi), PARAMETER      :: NStC4_Mxi    =  74
   INTEGER(IntKi), PARAMETER      :: NStC4_Myi    =  75
   INTEGER(IntKi), PARAMETER      :: NStC4_Mzi    =  76
   INTEGER(IntKi), PARAMETER      :: NStC4_Fxl    =  77
   INTEGER(IntKi), PARAMETER      :: NStC4_Fyl    =  78
   INTEGER(IntKi), PARAMETER      :: NStC4_Fzl    =  79
   INTEGER(IntKi), PARAMETER      :: NStC4_Mxl    =  80
   INTEGER(IntKi), PARAMETER      :: NStC4_Myl    =  81
   INTEGER(IntKi), PARAMETER      :: NStC4_Mzl    =  82


     ! Tower Structural Control  (StC):

   INTEGER(IntKi), PARAMETER      :: TStC1_XQ     =  83
   INTEGER(IntKi), PARAMETER      :: TStC1_XQD    =  84
   INTEGER(IntKi), PARAMETER      :: TStC1_YQ     =  85
   INTEGER(IntKi), PARAMETER      :: TStC1_YQD    =  86
   INTEGER(IntKi), PARAMETER      :: TStC1_ZQ     =  87
   INTEGER(IntKi), PARAMETER      :: TStC1_ZQD    =  88
   INTEGER(IntKi), PARAMETER      :: TStC1_Fxi    =  89
   INTEGER(IntKi), PARAMETER      :: TStC1_Fyi    =  90
   INTEGER(IntKi), PARAMETER      :: TStC1_Fzi    =  91
   INTEGER(IntKi), PARAMETER      :: TStC1_Mxi    =  92
   INTEGER(IntKi), PARAMETER      :: TStC1_Myi    =  93
   INTEGER(IntKi), PARAMETER      :: TStC1_Mzi    =  94
   INTEGER(IntKi), PARAMETER      :: TStC1_Fxl    =  95
   INTEGER(IntKi), PARAMETER      :: TStC1_Fyl    =  96
   INTEGER(IntKi), PARAMETER      :: TStC1_Fzl    =  97
   INTEGER(IntKi), PARAMETER      :: TStC1_Mxl    =  98
   INTEGER(IntKi), PARAMETER      :: TStC1_Myl    =  99
   INTEGER(IntKi), PARAMETER      :: TStC1_Mzl    = 100
   INTEGER(IntKi), PARAMETER      :: TStC2_XQ     = 101
   INTEGER(IntKi), PARAMETER      :: TStC2_XQD    = 102
   INTEGER(IntKi), PARAMETER      :: TStC2_YQ     = 103
   INTEGER(IntKi), PARAMETER      :: TStC2_YQD    = 104
   INTEGER(IntKi), PARAMETER      :: TStC2_ZQ     = 105
   INTEGER(IntKi), PARAMETER      :: TStC2_ZQD    = 106
   INTEGER(IntKi), PARAMETER      :: TStC2_Fxi    = 107
   INTEGER(IntKi), PARAMETER      :: TStC2_Fyi    = 108
   INTEGER(IntKi), PARAMETER      :: TStC2_Fzi    = 109
   INTEGER(IntKi), PARAMETER      :: TStC2_Mxi    = 110
   INTEGER(IntKi), PARAMETER      :: TStC2_Myi    = 111
   INTEGER(IntKi), PARAMETER      :: TStC2_Mzi    = 112
   INTEGER(IntKi), PARAMETER      :: TStC2_Fxl    = 113
   INTEGER(IntKi), PARAMETER      :: TStC2_Fyl    = 114
   INTEGER(IntKi), PARAMETER      :: TStC2_Fzl    = 115
   INTEGER(IntKi), PARAMETER      :: TStC2_Mxl    = 116
   INTEGER(IntKi), PARAMETER      :: TStC2_Myl    = 117
   INTEGER(IntKi), PARAMETER      :: TStC2_Mzl    = 118
   INTEGER(IntKi), PARAMETER      :: TStC3_XQ     = 119
   INTEGER(IntKi), PARAMETER      :: TStC3_XQD    = 120
   INTEGER(IntKi), PARAMETER      :: TStC3_YQ     = 121
   INTEGER(IntKi), PARAMETER      :: TStC3_YQD    = 122
   INTEGER(IntKi), PARAMETER      :: TStC3_ZQ     = 123
   INTEGER(IntKi), PARAMETER      :: TStC3_ZQD    = 124
   INTEGER(IntKi), PARAMETER      :: TStC3_Fxi    = 125
   INTEGER(IntKi), PARAMETER      :: TStC3_Fyi    = 126
   INTEGER(IntKi), PARAMETER      :: TStC3_Fzi    = 127
   INTEGER(IntKi), PARAMETER      :: TStC3_Mxi    = 128
   INTEGER(IntKi), PARAMETER      :: TStC3_Myi    = 129
   INTEGER(IntKi), PARAMETER      :: TStC3_Mzi    = 130
   INTEGER(IntKi), PARAMETER      :: TStC3_Fxl    = 131
   INTEGER(IntKi), PARAMETER      :: TStC3_Fyl    = 132
   INTEGER(IntKi), PARAMETER      :: TStC3_Fzl    = 133
   INTEGER(IntKi), PARAMETER      :: TStC3_Mxl    = 134
   INTEGER(IntKi), PARAMETER      :: TStC3_Myl    = 135
   INTEGER(IntKi), PARAMETER      :: TStC3_Mzl    = 136
   INTEGER(IntKi), PARAMETER      :: TStC4_XQ     = 137
   INTEGER(IntKi), PARAMETER      :: TStC4_XQD    = 138
   INTEGER(IntKi), PARAMETER      :: TStC4_YQ     = 139
   INTEGER(IntKi), PARAMETER      :: TStC4_YQD    = 140
   INTEGER(IntKi), PARAMETER      :: TStC4_ZQ     = 141
   INTEGER(IntKi), PARAMETER      :: TStC4_ZQD    = 142
   INTEGER(IntKi), PARAMETER      :: TStC4_Fxi    = 143
   INTEGER(IntKi), PARAMETER      :: TStC4_Fyi    = 144
   INTEGER(IntKi), PARAMETER      :: TStC4_Fzi    = 145
   INTEGER(IntKi), PARAMETER      :: TStC4_Mxi    = 146
   INTEGER(IntKi), PARAMETER      :: TStC4_Myi    = 147
   INTEGER(IntKi), PARAMETER      :: TStC4_Mzi    = 148
   INTEGER(IntKi), PARAMETER      :: TStC4_Fxl    = 149
   INTEGER(IntKi), PARAMETER      :: TStC4_Fyl    = 150
   INTEGER(IntKi), PARAMETER      :: TStC4_Fzl    = 151
   INTEGER(IntKi), PARAMETER      :: TStC4_Mxl    = 152
   INTEGER(IntKi), PARAMETER      :: TStC4_Myl    = 153
   INTEGER(IntKi), PARAMETER      :: TStC4_Mzl    = 154


     ! Blade  Structural Control  (StC):

   INTEGER(IntKi), PARAMETER      :: BStC1_B1_XQ  = 155
   INTEGER(IntKi), PARAMETER      :: BStC1_B1_XQD = 156
   INTEGER(IntKi), PARAMETER      :: BStC1_B1_YQ  = 157
   INTEGER(IntKi), PARAMETER      :: BStC1_B1_YQD = 158
   INTEGER(IntKi), PARAMETER      :: BStC1_B1_ZQ  = 159
   INTEGER(IntKi), PARAMETER      :: BStC1_B1_ZQD = 160
   INTEGER(IntKi), PARAMETER      :: BStC1_B1_Fxi = 161
   INTEGER(IntKi), PARAMETER      :: BStC1_B1_Fyi = 162
   INTEGER(IntKi), PARAMETER      :: BStC1_B1_Fzi = 163
   INTEGER(IntKi), PARAMETER      :: BStC1_B1_Mxi = 164
   INTEGER(IntKi), PARAMETER      :: BStC1_B1_Myi = 165
   INTEGER(IntKi), PARAMETER      :: BStC1_B1_Mzi = 166
   INTEGER(IntKi), PARAMETER      :: BStC1_B1_Fxl = 167
   INTEGER(IntKi), PARAMETER      :: BStC1_B1_Fyl = 168
   INTEGER(IntKi), PARAMETER      :: BStC1_B1_Fzl = 169
   INTEGER(IntKi), PARAMETER      :: BStC1_B1_Mxl = 170
   INTEGER(IntKi), PARAMETER      :: BStC1_B1_Myl = 171
   INTEGER(IntKi), PARAMETER      :: BStC1_B1_Mzl = 172
   INTEGER(IntKi), PARAMETER      :: BStC2_B1_XQ  = 173
   INTEGER(IntKi), PARAMETER      :: BStC2_B1_XQD = 174
   INTEGER(IntKi), PARAMETER      :: BStC2_B1_YQ  = 175
   INTEGER(IntKi), PARAMETER      :: BStC2_B1_YQD = 176
   INTEGER(IntKi), PARAMETER      :: BStC2_B1_ZQ  = 177
   INTEGER(IntKi), PARAMETER      :: BStC2_B1_ZQD = 178
   INTEGER(IntKi), PARAMETER      :: BStC2_B1_Fxi = 179
   INTEGER(IntKi), PARAMETER      :: BStC2_B1_Fyi = 180
   INTEGER(IntKi), PARAMETER      :: BStC2_B1_Fzi = 181
   INTEGER(IntKi), PARAMETER      :: BStC2_B1_Mxi = 182
   INTEGER(IntKi), PARAMETER      :: BStC2_B1_Myi = 183
   INTEGER(IntKi), PARAMETER      :: BStC2_B1_Mzi = 184
   INTEGER(IntKi), PARAMETER      :: BStC2_B1_Fxl = 185
   INTEGER(IntKi), PARAMETER      :: BStC2_B1_Fyl = 186
   INTEGER(IntKi), PARAMETER      :: BStC2_B1_Fzl = 187
   INTEGER(IntKi), PARAMETER      :: BStC2_B1_Mxl = 188
   INTEGER(IntKi), PARAMETER      :: BStC2_B1_Myl = 189
   INTEGER(IntKi), PARAMETER      :: BStC2_B1_Mzl = 190
   INTEGER(IntKi), PARAMETER      :: BStC3_B1_XQ  = 191
   INTEGER(IntKi), PARAMETER      :: BStC3_B1_XQD = 192
   INTEGER(IntKi), PARAMETER      :: BStC3_B1_YQ  = 193
   INTEGER(IntKi), PARAMETER      :: BStC3_B1_YQD = 194
   INTEGER(IntKi), PARAMETER      :: BStC3_B1_ZQ  = 195
   INTEGER(IntKi), PARAMETER      :: BStC3_B1_ZQD = 196
   INTEGER(IntKi), PARAMETER      :: BStC3_B1_Fxi = 197
   INTEGER(IntKi), PARAMETER      :: BStC3_B1_Fyi = 198
   INTEGER(IntKi), PARAMETER      :: BStC3_B1_Fzi = 199
   INTEGER(IntKi), PARAMETER      :: BStC3_B1_Mxi = 200
   INTEGER(IntKi), PARAMETER      :: BStC3_B1_Myi = 201
   INTEGER(IntKi), PARAMETER      :: BStC3_B1_Mzi = 202
   INTEGER(IntKi), PARAMETER      :: BStC3_B1_Fxl = 203
   INTEGER(IntKi), PARAMETER      :: BStC3_B1_Fyl = 204
   INTEGER(IntKi), PARAMETER      :: BStC3_B1_Fzl = 205
   INTEGER(IntKi), PARAMETER      :: BStC3_B1_Mxl = 206
   INTEGER(IntKi), PARAMETER      :: BStC3_B1_Myl = 207
   INTEGER(IntKi), PARAMETER      :: BStC3_B1_Mzl = 208
   INTEGER(IntKi), PARAMETER      :: BStC4_B1_XQ  = 209
   INTEGER(IntKi), PARAMETER      :: BStC4_B1_XQD = 210
   INTEGER(IntKi), PARAMETER      :: BStC4_B1_YQ  = 211
   INTEGER(IntKi), PARAMETER      :: BStC4_B1_YQD = 212
   INTEGER(IntKi), PARAMETER      :: BStC4_B1_ZQ  = 213
   INTEGER(IntKi), PARAMETER      :: BStC4_B1_ZQD = 214
   INTEGER(IntKi), PARAMETER      :: BStC4_B1_Fxi = 215
   INTEGER(IntKi), PARAMETER      :: BStC4_B1_Fyi = 216
   INTEGER(IntKi), PARAMETER      :: BStC4_B1_Fzi = 217
   INTEGER(IntKi), PARAMETER      :: BStC4_B1_Mxi = 218
   INTEGER(IntKi), PARAMETER      :: BStC4_B1_Myi = 219
   INTEGER(IntKi), PARAMETER      :: BStC4_B1_Mzi = 220
   INTEGER(IntKi), PARAMETER      :: BStC4_B1_Fxl = 221
   INTEGER(IntKi), PARAMETER      :: BStC4_B1_Fyl = 222
   INTEGER(IntKi), PARAMETER      :: BStC4_B1_Fzl = 223
   INTEGER(IntKi), PARAMETER      :: BStC4_B1_Mxl = 224
   INTEGER(IntKi), PARAMETER      :: BStC4_B1_Myl = 225
   INTEGER(IntKi), PARAMETER      :: BStC4_B1_Mzl = 226
   INTEGER(IntKi), PARAMETER      :: BStC1_B2_XQ  = 227
   INTEGER(IntKi), PARAMETER      :: BStC1_B2_XQD = 228
   INTEGER(IntKi), PARAMETER      :: BStC1_B2_YQ  = 229
   INTEGER(IntKi), PARAMETER      :: BStC1_B2_YQD = 230
   INTEGER(IntKi), PARAMETER      :: BStC1_B2_ZQ  = 231
   INTEGER(IntKi), PARAMETER      :: BStC1_B2_ZQD = 232
   INTEGER(IntKi), PARAMETER      :: BStC1_B2_Fxi = 233
   INTEGER(IntKi), PARAMETER      :: BStC1_B2_Fyi = 234
   INTEGER(IntKi), PARAMETER      :: BStC1_B2_Fzi = 235
   INTEGER(IntKi), PARAMETER      :: BStC1_B2_Mxi = 236
   INTEGER(IntKi), PARAMETER      :: BStC1_B2_Myi = 237
   INTEGER(IntKi), PARAMETER      :: BStC1_B2_Mzi = 238
   INTEGER(IntKi), PARAMETER      :: BStC1_B2_Fxl = 239
   INTEGER(IntKi), PARAMETER      :: BStC1_B2_Fyl = 240
   INTEGER(IntKi), PARAMETER      :: BStC1_B2_Fzl = 241
   INTEGER(IntKi), PARAMETER      :: BStC1_B2_Mxl = 242
   INTEGER(IntKi), PARAMETER      :: BStC1_B2_Myl = 243
   INTEGER(IntKi), PARAMETER      :: BStC1_B2_Mzl = 244
   INTEGER(IntKi), PARAMETER      :: BStC2_B2_XQ  = 245
   INTEGER(IntKi), PARAMETER      :: BStC2_B2_XQD = 246
   INTEGER(IntKi), PARAMETER      :: BStC2_B2_YQ  = 247
   INTEGER(IntKi), PARAMETER      :: BStC2_B2_YQD = 248
   INTEGER(IntKi), PARAMETER      :: BStC2_B2_ZQ  = 249
   INTEGER(IntKi), PARAMETER      :: BStC2_B2_ZQD = 250
   INTEGER(IntKi), PARAMETER      :: BStC2_B2_Fxi = 251
   INTEGER(IntKi), PARAMETER      :: BStC2_B2_Fyi = 252
   INTEGER(IntKi), PARAMETER      :: BStC2_B2_Fzi = 253
   INTEGER(IntKi), PARAMETER      :: BStC2_B2_Mxi = 254
   INTEGER(IntKi), PARAMETER      :: BStC2_B2_Myi = 255
   INTEGER(IntKi), PARAMETER      :: BStC2_B2_Mzi = 256
   INTEGER(IntKi), PARAMETER      :: BStC2_B2_Fxl = 257
   INTEGER(IntKi), PARAMETER      :: BStC2_B2_Fyl = 258
   INTEGER(IntKi), PARAMETER      :: BStC2_B2_Fzl = 259
   INTEGER(IntKi), PARAMETER      :: BStC2_B2_Mxl = 260
   INTEGER(IntKi), PARAMETER      :: BStC2_B2_Myl = 261
   INTEGER(IntKi), PARAMETER      :: BStC2_B2_Mzl = 262
   INTEGER(IntKi), PARAMETER      :: BStC3_B2_XQ  = 263
   INTEGER(IntKi), PARAMETER      :: BStC3_B2_XQD = 264
   INTEGER(IntKi), PARAMETER      :: BStC3_B2_YQ  = 265
   INTEGER(IntKi), PARAMETER      :: BStC3_B2_YQD = 266
   INTEGER(IntKi), PARAMETER      :: BStC3_B2_ZQ  = 267
   INTEGER(IntKi), PARAMETER      :: BStC3_B2_ZQD = 268
   INTEGER(IntKi), PARAMETER      :: BStC3_B2_Fxi = 269
   INTEGER(IntKi), PARAMETER      :: BStC3_B2_Fyi = 270
   INTEGER(IntKi), PARAMETER      :: BStC3_B2_Fzi = 271
   INTEGER(IntKi), PARAMETER      :: BStC3_B2_Mxi = 272
   INTEGER(IntKi), PARAMETER      :: BStC3_B2_Myi = 273
   INTEGER(IntKi), PARAMETER      :: BStC3_B2_Mzi = 274
   INTEGER(IntKi), PARAMETER      :: BStC3_B2_Fxl = 275
   INTEGER(IntKi), PARAMETER      :: BStC3_B2_Fyl = 276
   INTEGER(IntKi), PARAMETER      :: BStC3_B2_Fzl = 277
   INTEGER(IntKi), PARAMETER      :: BStC3_B2_Mxl = 278
   INTEGER(IntKi), PARAMETER      :: BStC3_B2_Myl = 279
   INTEGER(IntKi), PARAMETER      :: BStC3_B2_Mzl = 280
   INTEGER(IntKi), PARAMETER      :: BStC4_B2_XQ  = 281
   INTEGER(IntKi), PARAMETER      :: BStC4_B2_XQD = 282
   INTEGER(IntKi), PARAMETER      :: BStC4_B2_YQ  = 283
   INTEGER(IntKi), PARAMETER      :: BStC4_B2_YQD = 284
   INTEGER(IntKi), PARAMETER      :: BStC4_B2_ZQ  = 285
   INTEGER(IntKi), PARAMETER      :: BStC4_B2_ZQD = 286
   INTEGER(IntKi), PARAMETER      :: BStC4_B2_Fxi = 287
   INTEGER(IntKi), PARAMETER      :: BStC4_B2_Fyi = 288
   INTEGER(IntKi), PARAMETER      :: BStC4_B2_Fzi = 289
   INTEGER(IntKi), PARAMETER      :: BStC4_B2_Mxi = 290
   INTEGER(IntKi), PARAMETER      :: BStC4_B2_Myi = 291
   INTEGER(IntKi), PARAMETER      :: BStC4_B2_Mzi = 292
   INTEGER(IntKi), PARAMETER      :: BStC4_B2_Fxl = 293
   INTEGER(IntKi), PARAMETER      :: BStC4_B2_Fyl = 294
   INTEGER(IntKi), PARAMETER      :: BStC4_B2_Fzl = 295
   INTEGER(IntKi), PARAMETER      :: BStC4_B2_Mxl = 296
   INTEGER(IntKi), PARAMETER      :: BStC4_B2_Myl = 297
   INTEGER(IntKi), PARAMETER      :: BStC4_B2_Mzl = 298
   INTEGER(IntKi), PARAMETER      :: BStC1_B3_XQ  = 299
   INTEGER(IntKi), PARAMETER      :: BStC1_B3_XQD = 300
   INTEGER(IntKi), PARAMETER      :: BStC1_B3_YQ  = 301
   INTEGER(IntKi), PARAMETER      :: BStC1_B3_YQD = 302
   INTEGER(IntKi), PARAMETER      :: BStC1_B3_ZQ  = 303
   INTEGER(IntKi), PARAMETER      :: BStC1_B3_ZQD = 304
   INTEGER(IntKi), PARAMETER      :: BStC1_B3_Fxi = 305
   INTEGER(IntKi), PARAMETER      :: BStC1_B3_Fyi = 306
   INTEGER(IntKi), PARAMETER      :: BStC1_B3_Fzi = 307
   INTEGER(IntKi), PARAMETER      :: BStC1_B3_Mxi = 308
   INTEGER(IntKi), PARAMETER      :: BStC1_B3_Myi = 309
   INTEGER(IntKi), PARAMETER      :: BStC1_B3_Mzi = 310
   INTEGER(IntKi), PARAMETER      :: BStC1_B3_Fxl = 311
   INTEGER(IntKi), PARAMETER      :: BStC1_B3_Fyl = 312
   INTEGER(IntKi), PARAMETER      :: BStC1_B3_Fzl = 313
   INTEGER(IntKi), PARAMETER      :: BStC1_B3_Mxl = 314
   INTEGER(IntKi), PARAMETER      :: BStC1_B3_Myl = 315
   INTEGER(IntKi), PARAMETER      :: BStC1_B3_Mzl = 316
   INTEGER(IntKi), PARAMETER      :: BStC2_B3_XQ  = 317
   INTEGER(IntKi), PARAMETER      :: BStC2_B3_XQD = 318
   INTEGER(IntKi), PARAMETER      :: BStC2_B3_YQ  = 319
   INTEGER(IntKi), PARAMETER      :: BStC2_B3_YQD = 320
   INTEGER(IntKi), PARAMETER      :: BStC2_B3_ZQ  = 321
   INTEGER(IntKi), PARAMETER      :: BStC2_B3_ZQD = 322
   INTEGER(IntKi), PARAMETER      :: BStC2_B3_Fxi = 323
   INTEGER(IntKi), PARAMETER      :: BStC2_B3_Fyi = 324
   INTEGER(IntKi), PARAMETER      :: BStC2_B3_Fzi = 325
   INTEGER(IntKi), PARAMETER      :: BStC2_B3_Mxi = 326
   INTEGER(IntKi), PARAMETER      :: BStC2_B3_Myi = 327
   INTEGER(IntKi), PARAMETER      :: BStC2_B3_Mzi = 328
   INTEGER(IntKi), PARAMETER      :: BStC2_B3_Fxl = 329
   INTEGER(IntKi), PARAMETER      :: BStC2_B3_Fyl = 330
   INTEGER(IntKi), PARAMETER      :: BStC2_B3_Fzl = 331
   INTEGER(IntKi), PARAMETER      :: BStC2_B3_Mxl = 332
   INTEGER(IntKi), PARAMETER      :: BStC2_B3_Myl = 333
   INTEGER(IntKi), PARAMETER      :: BStC2_B3_Mzl = 334
   INTEGER(IntKi), PARAMETER      :: BStC3_B3_XQ  = 335
   INTEGER(IntKi), PARAMETER      :: BStC3_B3_XQD = 336
   INTEGER(IntKi), PARAMETER      :: BStC3_B3_YQ  = 337
   INTEGER(IntKi), PARAMETER      :: BStC3_B3_YQD = 338
   INTEGER(IntKi), PARAMETER      :: BStC3_B3_ZQ  = 339
   INTEGER(IntKi), PARAMETER      :: BStC3_B3_ZQD = 340
   INTEGER(IntKi), PARAMETER      :: BStC3_B3_Fxi = 341
   INTEGER(IntKi), PARAMETER      :: BStC3_B3_Fyi = 342
   INTEGER(IntKi), PARAMETER      :: BStC3_B3_Fzi = 343
   INTEGER(IntKi), PARAMETER      :: BStC3_B3_Mxi = 344
   INTEGER(IntKi), PARAMETER      :: BStC3_B3_Myi = 345
   INTEGER(IntKi), PARAMETER      :: BStC3_B3_Mzi = 346
   INTEGER(IntKi), PARAMETER      :: BStC3_B3_Fxl = 347
   INTEGER(IntKi), PARAMETER      :: BStC3_B3_Fyl = 348
   INTEGER(IntKi), PARAMETER      :: BStC3_B3_Fzl = 349
   INTEGER(IntKi), PARAMETER      :: BStC3_B3_Mxl = 350
   INTEGER(IntKi), PARAMETER      :: BStC3_B3_Myl = 351
   INTEGER(IntKi), PARAMETER      :: BStC3_B3_Mzl = 352
   INTEGER(IntKi), PARAMETER      :: BStC4_B3_XQ  = 353
   INTEGER(IntKi), PARAMETER      :: BStC4_B3_XQD = 354
   INTEGER(IntKi), PARAMETER      :: BStC4_B3_YQ  = 355
   INTEGER(IntKi), PARAMETER      :: BStC4_B3_YQD = 356
   INTEGER(IntKi), PARAMETER      :: BStC4_B3_ZQ  = 357
   INTEGER(IntKi), PARAMETER      :: BStC4_B3_ZQD = 358
   INTEGER(IntKi), PARAMETER      :: BStC4_B3_Fxi = 359
   INTEGER(IntKi), PARAMETER      :: BStC4_B3_Fyi = 360
   INTEGER(IntKi), PARAMETER      :: BStC4_B3_Fzi = 361
   INTEGER(IntKi), PARAMETER      :: BStC4_B3_Mxi = 362
   INTEGER(IntKi), PARAMETER      :: BStC4_B3_Myi = 363
   INTEGER(IntKi), PARAMETER      :: BStC4_B3_Mzi = 364
   INTEGER(IntKi), PARAMETER      :: BStC4_B3_Fxl = 365
   INTEGER(IntKi), PARAMETER      :: BStC4_B3_Fyl = 366
   INTEGER(IntKi), PARAMETER      :: BStC4_B3_Fzl = 367
   INTEGER(IntKi), PARAMETER      :: BStC4_B3_Mxl = 368
   INTEGER(IntKi), PARAMETER      :: BStC4_B3_Myl = 369
   INTEGER(IntKi), PARAMETER      :: BStC4_B3_Mzl = 370
   INTEGER(IntKi), PARAMETER      :: BStC1_B4_XQ  = 371
   INTEGER(IntKi), PARAMETER      :: BStC1_B4_XQD = 372
   INTEGER(IntKi), PARAMETER      :: BStC1_B4_YQ  = 373
   INTEGER(IntKi), PARAMETER      :: BStC1_B4_YQD = 374
   INTEGER(IntKi), PARAMETER      :: BStC1_B4_ZQ  = 375
   INTEGER(IntKi), PARAMETER      :: BStC1_B4_ZQD = 376
   INTEGER(IntKi), PARAMETER      :: BStC1_B4_Fxi = 377
   INTEGER(IntKi), PARAMETER      :: BStC1_B4_Fyi = 378
   INTEGER(IntKi), PARAMETER      :: BStC1_B4_Fzi = 379
   INTEGER(IntKi), PARAMETER      :: BStC1_B4_Mxi = 380
   INTEGER(IntKi), PARAMETER      :: BStC1_B4_Myi = 381
   INTEGER(IntKi), PARAMETER      :: BStC1_B4_Mzi = 382
   INTEGER(IntKi), PARAMETER      :: BStC1_B4_Fxl = 383
   INTEGER(IntKi), PARAMETER      :: BStC1_B4_Fyl = 384
   INTEGER(IntKi), PARAMETER      :: BStC1_B4_Fzl = 385
   INTEGER(IntKi), PARAMETER      :: BStC1_B4_Mxl = 386
   INTEGER(IntKi), PARAMETER      :: BStC1_B4_Myl = 387
   INTEGER(IntKi), PARAMETER      :: BStC1_B4_Mzl = 388
   INTEGER(IntKi), PARAMETER      :: BStC2_B4_XQ  = 389
   INTEGER(IntKi), PARAMETER      :: BStC2_B4_XQD = 390
   INTEGER(IntKi), PARAMETER      :: BStC2_B4_YQ  = 391
   INTEGER(IntKi), PARAMETER      :: BStC2_B4_YQD = 392
   INTEGER(IntKi), PARAMETER      :: BStC2_B4_ZQ  = 393
   INTEGER(IntKi), PARAMETER      :: BStC2_B4_ZQD = 394
   INTEGER(IntKi), PARAMETER      :: BStC2_B4_Fxi = 395
   INTEGER(IntKi), PARAMETER      :: BStC2_B4_Fyi = 396
   INTEGER(IntKi), PARAMETER      :: BStC2_B4_Fzi = 397
   INTEGER(IntKi), PARAMETER      :: BStC2_B4_Mxi = 398
   INTEGER(IntKi), PARAMETER      :: BStC2_B4_Myi = 399
   INTEGER(IntKi), PARAMETER      :: BStC2_B4_Mzi = 400
   INTEGER(IntKi), PARAMETER      :: BStC2_B4_Fxl = 401
   INTEGER(IntKi), PARAMETER      :: BStC2_B4_Fyl = 402
   INTEGER(IntKi), PARAMETER      :: BStC2_B4_Fzl = 403
   INTEGER(IntKi), PARAMETER      :: BStC2_B4_Mxl = 404
   INTEGER(IntKi), PARAMETER      :: BStC2_B4_Myl = 405
   INTEGER(IntKi), PARAMETER      :: BStC2_B4_Mzl = 406
   INTEGER(IntKi), PARAMETER      :: BStC3_B4_XQ  = 407
   INTEGER(IntKi), PARAMETER      :: BStC3_B4_XQD = 408
   INTEGER(IntKi), PARAMETER      :: BStC3_B4_YQ  = 409
   INTEGER(IntKi), PARAMETER      :: BStC3_B4_YQD = 410
   INTEGER(IntKi), PARAMETER      :: BStC3_B4_ZQ  = 411
   INTEGER(IntKi), PARAMETER      :: BStC3_B4_ZQD = 412
   INTEGER(IntKi), PARAMETER      :: BStC3_B4_Fxi = 413
   INTEGER(IntKi), PARAMETER      :: BStC3_B4_Fyi = 414
   INTEGER(IntKi), PARAMETER      :: BStC3_B4_Fzi = 415
   INTEGER(IntKi), PARAMETER      :: BStC3_B4_Mxi = 416
   INTEGER(IntKi), PARAMETER      :: BStC3_B4_Myi = 417
   INTEGER(IntKi), PARAMETER      :: BStC3_B4_Mzi = 418
   INTEGER(IntKi), PARAMETER      :: BStC3_B4_Fxl = 419
   INTEGER(IntKi), PARAMETER      :: BStC3_B4_Fyl = 420
   INTEGER(IntKi), PARAMETER      :: BStC3_B4_Fzl = 421
   INTEGER(IntKi), PARAMETER      :: BStC3_B4_Mxl = 422
   INTEGER(IntKi), PARAMETER      :: BStC3_B4_Myl = 423
   INTEGER(IntKi), PARAMETER      :: BStC3_B4_Mzl = 424
   INTEGER(IntKi), PARAMETER      :: BStC4_B4_XQ  = 425
   INTEGER(IntKi), PARAMETER      :: BStC4_B4_XQD = 426
   INTEGER(IntKi), PARAMETER      :: BStC4_B4_YQ  = 427
   INTEGER(IntKi), PARAMETER      :: BStC4_B4_YQD = 428
   INTEGER(IntKi), PARAMETER      :: BStC4_B4_ZQ  = 429
   INTEGER(IntKi), PARAMETER      :: BStC4_B4_ZQD = 430
   INTEGER(IntKi), PARAMETER      :: BStC4_B4_Fxi = 431
   INTEGER(IntKi), PARAMETER      :: BStC4_B4_Fyi = 432
   INTEGER(IntKi), PARAMETER      :: BStC4_B4_Fzi = 433
   INTEGER(IntKi), PARAMETER      :: BStC4_B4_Mxi = 434
   INTEGER(IntKi), PARAMETER      :: BStC4_B4_Myi = 435
   INTEGER(IntKi), PARAMETER      :: BStC4_B4_Mzi = 436
   INTEGER(IntKi), PARAMETER      :: BStC4_B4_Fxl = 437
   INTEGER(IntKi), PARAMETER      :: BStC4_B4_Fyl = 438
   INTEGER(IntKi), PARAMETER      :: BStC4_B4_Fzl = 439
   INTEGER(IntKi), PARAMETER      :: BStC4_B4_Mxl = 440
   INTEGER(IntKi), PARAMETER      :: BStC4_B4_Myl = 441
   INTEGER(IntKi), PARAMETER      :: BStC4_B4_Mzl = 442


     ! Substructure  Structural Control  (StC):

   INTEGER(IntKi), PARAMETER      :: SStC1_XQ     = 443
   INTEGER(IntKi), PARAMETER      :: SStC1_XQD    = 444
   INTEGER(IntKi), PARAMETER      :: SStC1_YQ     = 445
   INTEGER(IntKi), PARAMETER      :: SStC1_YQD    = 446
   INTEGER(IntKi), PARAMETER      :: SStC1_ZQ     = 447
   INTEGER(IntKi), PARAMETER      :: SStC1_ZQD    = 448
   INTEGER(IntKi), PARAMETER      :: SStC1_bQ     = 449
   INTEGER(IntKi), PARAMETER      :: SStC1_bQD    = 450
   INTEGER(IntKi), PARAMETER      :: SStC1_Fxi    = 451
   INTEGER(IntKi), PARAMETER      :: SStC1_Fyi    = 452
   INTEGER(IntKi), PARAMETER      :: SStC1_Fzi    = 453
   INTEGER(IntKi), PARAMETER      :: SStC1_Mxi    = 454
   INTEGER(IntKi), PARAMETER      :: SStC1_Myi    = 455
   INTEGER(IntKi), PARAMETER      :: SStC1_Mzi    = 456
   INTEGER(IntKi), PARAMETER      :: SStC1_Fxl    = 457
   INTEGER(IntKi), PARAMETER      :: SStC1_Fyl    = 458
   INTEGER(IntKi), PARAMETER      :: SStC1_Fzl    = 459
   INTEGER(IntKi), PARAMETER      :: SStC1_Mxl    = 460
   INTEGER(IntKi), PARAMETER      :: SStC1_Myl    = 461
   INTEGER(IntKi), PARAMETER      :: SStC1_Mzl    = 462
   INTEGER(IntKi), PARAMETER      :: SStC2_XQ     = 463
   INTEGER(IntKi), PARAMETER      :: SStC2_XQD    = 464
   INTEGER(IntKi), PARAMETER      :: SStC2_YQ     = 465
   INTEGER(IntKi), PARAMETER      :: SStC2_YQD    = 466
   INTEGER(IntKi), PARAMETER      :: SStC2_ZQ     = 467
   INTEGER(IntKi), PARAMETER      :: SStC2_ZQD    = 468
   INTEGER(IntKi), PARAMETER      :: SStC2_bQ     = 469
   INTEGER(IntKi), PARAMETER      :: SStC2_bQD    = 470
   INTEGER(IntKi), PARAMETER      :: SStC2_Fxi    = 471
   INTEGER(IntKi), PARAMETER      :: SStC2_Fyi    = 472
   INTEGER(IntKi), PARAMETER      :: SStC2_Fzi    = 473
   INTEGER(IntKi), PARAMETER      :: SStC2_Mxi    = 474
   INTEGER(IntKi), PARAMETER      :: SStC2_Myi    = 475
   INTEGER(IntKi), PARAMETER      :: SStC2_Mzi    = 476
   INTEGER(IntKi), PARAMETER      :: SStC2_Fxl    = 477
   INTEGER(IntKi), PARAMETER      :: SStC2_Fyl    = 478
   INTEGER(IntKi), PARAMETER      :: SStC2_Fzl    = 479
   INTEGER(IntKi), PARAMETER      :: SStC2_Mxl    = 480
   INTEGER(IntKi), PARAMETER      :: SStC2_Myl    = 481
   INTEGER(IntKi), PARAMETER      :: SStC2_Mzl    = 482
   INTEGER(IntKi), PARAMETER      :: SStC3_XQ     = 483
   INTEGER(IntKi), PARAMETER      :: SStC3_XQD    = 484
   INTEGER(IntKi), PARAMETER      :: SStC3_YQ     = 485
   INTEGER(IntKi), PARAMETER      :: SStC3_YQD    = 486
   INTEGER(IntKi), PARAMETER      :: SStC3_ZQ     = 487
   INTEGER(IntKi), PARAMETER      :: SStC3_ZQD    = 488
   INTEGER(IntKi), PARAMETER      :: SStC3_bQ     = 489
   INTEGER(IntKi), PARAMETER      :: SStC3_bQD    = 490
   INTEGER(IntKi), PARAMETER      :: SStC3_Fxi    = 491
   INTEGER(IntKi), PARAMETER      :: SStC3_Fyi    = 492
   INTEGER(IntKi), PARAMETER      :: SStC3_Fzi    = 493
   INTEGER(IntKi), PARAMETER      :: SStC3_Mxi    = 494
   INTEGER(IntKi), PARAMETER      :: SStC3_Myi    = 495
   INTEGER(IntKi), PARAMETER      :: SStC3_Mzi    = 496
   INTEGER(IntKi), PARAMETER      :: SStC3_Fxl    = 497
   INTEGER(IntKi), PARAMETER      :: SStC3_Fyl    = 498
   INTEGER(IntKi), PARAMETER      :: SStC3_Fzl    = 499
   INTEGER(IntKi), PARAMETER      :: SStC3_Mxl    = 500
   INTEGER(IntKi), PARAMETER      :: SStC3_Myl    = 501
   INTEGER(IntKi), PARAMETER      :: SStC3_Mzl    = 502
   INTEGER(IntKi), PARAMETER      :: SStC4_XQ     = 503
   INTEGER(IntKi), PARAMETER      :: SStC4_XQD    = 504
   INTEGER(IntKi), PARAMETER      :: SStC4_YQ     = 505
   INTEGER(IntKi), PARAMETER      :: SStC4_YQD    = 506
   INTEGER(IntKi), PARAMETER      :: SStC4_ZQ     = 507
   INTEGER(IntKi), PARAMETER      :: SStC4_ZQD    = 508
   INTEGER(IntKi), PARAMETER      :: SStC4_bQ     = 509
   INTEGER(IntKi), PARAMETER      :: SStC4_bQD    = 510
   INTEGER(IntKi), PARAMETER      :: SStC4_Fxi    = 511
   INTEGER(IntKi), PARAMETER      :: SStC4_Fyi    = 512
   INTEGER(IntKi), PARAMETER      :: SStC4_Fzi    = 513
   INTEGER(IntKi), PARAMETER      :: SStC4_Mxi    = 514
   INTEGER(IntKi), PARAMETER      :: SStC4_Myi    = 515
   INTEGER(IntKi), PARAMETER      :: SStC4_Mzi    = 516
   INTEGER(IntKi), PARAMETER      :: SStC4_Fxl    = 517
   INTEGER(IntKi), PARAMETER      :: SStC4_Fyl    = 518
   INTEGER(IntKi), PARAMETER      :: SStC4_Fzl    = 519
   INTEGER(IntKi), PARAMETER      :: SStC4_Mxl    = 520
   INTEGER(IntKi), PARAMETER      :: SStC4_Myl    = 521
   INTEGER(IntKi), PARAMETER      :: SStC4_Mzl    = 522


     ! The maximum number of output channels which can be output by the code.
   INTEGER(IntKi), PARAMETER      :: MaxOutPts    = 522

!End of code generated by Matlab script Write_ChckOutLst
! ===================================================================================================
